from __future__ import annotations

import unittest
from pathlib import Path

import pyscf_agent.web.ui as web_ui


WEB_ASSET_DIR = Path(__file__).resolve().parents[2] / 'pyscf_agent' / 'web_assets'
ASSISTANT_SOURCE_ASSETS = (
    'assistant.css',
    'molecular-preview.css',
    'molecular-preview.js',
    'assistant-core.js',
    'assistant-sessions.js',
    'assistant-structures.js',
    'assistant-forms.js',
    'assistant-results.js',
    'assistant-actions.js',
    'assistant-init.js',
)


def assistant_ui_source(page_html: str) -> str:
    sources = [page_html]
    sources.extend(
        (WEB_ASSET_DIR / asset_name).read_text(encoding='utf-8')
        for asset_name in ASSISTANT_SOURCE_ASSETS
    )
    return '\n'.join(sources)


class DummyLLMBuilder:
    @staticmethod
    def get_llm_cache_scope():
        return 'llm:test:supported'


class WebUiTests(unittest.TestCase):
    def test_all_calculation_families_share_the_confirmed_run_lifecycle(self):
        actions_source = (WEB_ASSET_DIR / 'assistant-actions.js').read_text(encoding='utf-8')
        run_agent_start = actions_source.index('async function runAgent()')
        run_agent_source = actions_source[run_agent_start:]

        self.assertIn("if (task_spec.task_type === 'model_hamiltonian')", run_agent_source)
        self.assertIn("if (task_spec.task_type === 'periodic')", run_agent_source)
        self.assertEqual(run_agent_source.count('renderComputeConfirmPanel('), 3)
        self.assertNotIn('executePreparedRequest(', run_agent_source)
        self.assertIn('await executePreparedRequest(pendingExecutionRequest);', actions_source)
        self.assertIn("postCalculationLifecycle('/api/run-submit'", actions_source)
        self.assertIn("postCalculationLifecycle('/api/run-cancel'", actions_source)
        self.assertIn("postCalculationLifecycle('/api/task-review-action'", actions_source)

    def test_submitted_job_status_can_be_refreshed_and_collected_after_polling_stops(self):
        html = (WEB_ASSET_DIR / 'assistant_index.html').read_text(encoding='utf-8')
        actions_source = (WEB_ASSET_DIR / 'assistant-actions.js').read_text(encoding='utf-8')
        sessions_source = (WEB_ASSET_DIR / 'assistant-sessions.js').read_text(encoding='utf-8')
        init_source = (WEB_ASSET_DIR / 'assistant-init.js').read_text(encoding='utf-8')
        execute_start = actions_source.index('async function executePreparedRequest(')
        execute_end = actions_source.index('async function analyzeCurrentResult()', execute_start)
        execute_source = actions_source[execute_start:execute_end]

        self.assertIn('id="refresh-status"', html)
        self.assertIn('async function refreshActiveRunStatus()', actions_source)
        self.assertIn("postCalculationLifecycle('/api/run-status'", actions_source)
        self.assertIn('status.report_available', actions_source)
        self.assertIn('collectSubmittedRun(handle, activeRunPreparedRequestText', actions_source)
        self.assertIn("t('runConnectionInterrupted')", actions_source)
        self.assertNotIn('activeRunHandle = null;', execute_source)
        self.assertIn('session.activeRunHandle = activeRunHandle', sessions_source)
        self.assertIn('activeRunHandle = session.activeRunHandle', sessions_source)
        self.assertIn("renderStatus(activeRunLastState);", sessions_source)
        self.assertIn(
            "document.getElementById('refresh-status').addEventListener('click', refreshActiveRunStatus);",
            init_source,
        )

    def test_model_messages_use_the_shared_hamiltonian_edit_endpoint(self):
        actions_source = (WEB_ASSET_DIR / 'assistant-actions.js').read_text(encoding='utf-8')
        helper_start = actions_source.index('async function prepareModelHamiltonianEdit(')
        run_start = actions_source.index('async function runAgent()', helper_start)
        helper_source = actions_source[helper_start:run_start]
        run_source = actions_source[run_start:]

        self.assertIn("fetch('/api/model-hamiltonian-edit'", helper_source)
        self.assertIn('lifecycle: currentTaskLifecycle', helper_source)
        self.assertIn('updateCurrentTaskLifecycle(prepared);', helper_source)
        self.assertIn('applyTaskSpecToForm(pendingStructuredRequest);', helper_source)
        self.assertIn('await previewModelHamiltonianStructure();', helper_source)
        self.assertIn('if (request) {', run_source)
        self.assertIn('await prepareModelHamiltonianEdit(task_spec, request);', run_source)

    def test_approval_advances_lifecycle_before_enabling_execution(self):
        actions_source = (WEB_ASSET_DIR / 'assistant-actions.js').read_text(encoding='utf-8')
        active_start = actions_source.index('async function approvePendingActiveSpace()')
        active_end = actions_source.index('async function approvePendingApproval()', active_start)
        active_source = actions_source[active_start:active_end]
        execute_start = actions_source.index('async function executePreparedRequest(')
        execute_end = actions_source.index('async function analyzeCurrentResult()', execute_start)
        execute_source = actions_source[execute_start:execute_end]

        self.assertLess(
            active_source.index("applyPendingApprovalLifecycle('approve', 'active_space')"),
            active_source.index('renderComputeConfirmPanel('),
        )
        self.assertLess(
            execute_source.index("postCalculationLifecycle('/api/run-submit'"),
            execute_source.index("content: t('runStarted')"),
        )

    def test_english_only_runtime_surfaces_do_not_embed_chinese_copy(self):
        template = (WEB_ASSET_DIR / 'assistant_index.html').read_text(encoding='utf-8')
        results_source = (WEB_ASSET_DIR / 'assistant-results.js').read_text(encoding='utf-8')
        block2_start = results_source.index('function renderBlock2Bars')
        block2_end = results_source.index('function activeSpaceAuditContract')

        self.assertNotRegex(template, r'[\u3400-\u9fff]')
        self.assertNotRegex(results_source[block2_start:block2_end], r'[\u3400-\u9fff]')

    def test_build_index_html_without_llm_builder_still_returns_page(self):
        html = web_ui.build_index_html()

        self.assertIn('<title>Calculation Assistant</title>', html)
        self.assertIn('<h1 id="hero-title">Calculation Assistant</h1>', html)
        self.assertIn('Individual task calculation', html)
        self.assertIn('let currentPrepareCacheScope = "llm:unknown";', html)
        self.assertRegex(html, r'<link rel="stylesheet" href="/assets/assistant\.css\?v=[0-9a-f]{12}">')
        self.assertRegex(html, r'<script src="/assets/assistant-core\.js\?v=[0-9a-f]{12}"></script>')
        self.assertLess(html.index('/assets/shared.js?v='), html.index('/assets/assistant-core.js?v='))

    def test_preparation_states_and_capability_guidance_are_explicit(self):
        html = assistant_ui_source(web_ui.build_index_html())

        self.assertIn('id="atom-validation" class="field-validation"', html)
        self.assertIn('function validateMolecularStructureBeforePrepare(request)', html)
        self.assertIn("missing_fields: ['atom']", html)
        self.assertIn("renderStatus(preparationStatus);", html)
        self.assertIn("prepared: t('statusPrepared')", html)
        self.assertIn("changed: t('statusChanged')", html)
        self.assertIn("updateActiveTaskSessionStatus('changed');", html)
        self.assertIn("t('configurationChangedMessage')", html)
        self.assertIn('id="active-space-solver-hint"', html)
        self.assertIn('data-optional-dependency="block2"', html)
        self.assertIn("t('block2SolverRequiresCas')", html)
        self.assertIn('id="task-family-effective"', html)
        self.assertIn('id="task-session-effective"', html)
        self.assertIn('@media (max-width: 1280px)', html)

    def test_build_index_html_preserves_javascript_newline_escapes(self):
        html = assistant_ui_source(
            web_ui.build_index_html(llm_request_builder_module=DummyLLMBuilder())
        )

        self.assertIn('let currentPrepareCacheScope = "llm:test:supported";', html)
        self.assertIn('id="lang-toggle"', html)
        self.assertIn('const TRANSLATIONS = {', html)
        self.assertIn('const LANGUAGE_SWITCH_ENABLED = false;', html)
        self.assertIn("let currentLanguage = 'en';", html)
        self.assertIn('id="lang-toggle" type="button" class="ghost" hidden disabled', html)
        self.assertIn('function updateStaticText()', html)
        self.assertIn('function setLanguage(nextLanguage)', html)
        self.assertIn('Assistant Conversation', html)
        self.assertIn('id="label-request">Message</strong>', html)
        self.assertNotIn('Shows system and assistant messages returned by the backend.', html)
        self.assertNotIn('展示 backend 返回的 system / assistant 消息。', html)
        self.assertIn('.message.system { background: #f8fafc; border: 1px dashed #cbd5e1; font-size: 0.82rem; text-align: center;', html)
        self.assertIn('.hero-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 1rem; }', html)
        self.assertIn('button.ghost { margin-top: 0; background: rgba(255, 255, 255, 0.92);', html)
        self.assertIn('.approval-panel.active { display: grid; gap: 0.85rem; }', html)
        self.assertIn('.conversation-action-bar { display: flex; align-items: center; justify-content: space-between;', html)
        self.assertIn('.conversation-action-bar button { width: auto; min-height: 2.45rem;', html)
        self.assertIn('.compute-confirm-panel { display: block; margin: 0; }', html)
        self.assertNotIn('.compute-confirm-panel { display: grid; gap: 0.85rem; border:', html)
        self.assertNotIn('.compute-confirm-panel.ready { border-color:', html)
        self.assertIn('.calculation-actions { display: flex; gap: 0.5rem; flex-wrap: wrap; align-items: center; }', html)
        self.assertIn('.task-setup-card { gap: 0.85rem; }', html)
        self.assertIn('#config-title { margin: 0; }', html)
        self.assertIn('const existingAssistantContents = new Set(', html)
        self.assertIn('formatRequestSource', html)
        self.assertIn('formatLlmCacheScope', html)
        self.assertIn('formatDefaultEntry', html)
        self.assertIn('function langText(enText)', html)
        self.assertIn('function labelForRole(role)', html)
        self.assertIn('function isParsedUserRequestMessage(item)', html)
        self.assertIn('function setSelectValue(selectId, value)', html)
        self.assertIn("xc: method === 'dft' ? document.getElementById('xc').value : null", html)
        self.assertIn("taskSpec.xc = null;", html)
        self.assertIn('<select id="density-fitting-auxbasis">', html)
        self.assertNotIn('id="density-fitting-auxbasis" type="text"', html)
        self.assertIn('<option value="__off__" selected>No density fitting</option>', html)
        self.assertIn('<option value="">PySCF auto</option>', html)
        self.assertIn('<option value="def2-svp-jkfit">def2-svp-jkfit</option>', html)
        self.assertIn('const AUXBASIS_RECOMMENDATIONS = {', html)
        self.assertIn('"sto-3g": ["def2-svp-jkfit", "def2-universal-jkfit", "weigend+etb"]', html)
        self.assertIn('function orderedAuxbasisOptionsForBasis', html)
        self.assertIn("document.getElementById('basis').addEventListener('change'", html)
        self.assertIn("density_fitting: {", html)
        self.assertIn("const densityFittingEnabled = densityFittingAuxbasis !== '__off__';", html)
        self.assertIn('auxbasis: densityFittingEnabled && densityFittingAuxbasis ? densityFittingAuxbasis : null', html)
        self.assertIn("apply_to: 'scf'", html)
        self.assertIn("setSelectValue('basis', taskSpec.basis);", html)
        self.assertIn("setSelectValue('xc', taskSpec.xc);", html)
        self.assertIn("select.appendChild(option);", html)
        self.assertIn('id="approval-panel"', html)
        self.assertIn('id="approval-assumptions"', html)
        self.assertIn('几何假设', html)
        self.assertIn('id="compute-confirm-panel"', html)
        self.assertIn('id="task-family"', html)
        self.assertIn('体系', html)
        self.assertIn('"labelTaskFamily": "System"', html)
        self.assertIn('id="task-session-select"', html)
        self.assertIn('id="new-task"', html)
        self.assertIn('function createTaskSession', html)
        self.assertIn('function switchTaskSession', html)
        self.assertIn('function snapshotCurrentTaskSession', html)
        self.assertIn('function restoreTaskSession', html)
        self.assertIn('"taskSessionsTitle": "Tasks"', html)
        self.assertIn('"builderInputLinked": "The model Hamiltonian input generated by the builder is linked to the current task."', html)
        self.assertNotIn('Calculation Target', html)
        self.assertIn('id="work-dir"', html)
        self.assertIn('Work Directory', html)
        self.assertIn('id="execution-target"', html)
        self.assertIn('"labelExecutionTarget": "Execution"', html)
        self.assertIn('id="resource-profile"', html)
        self.assertIn('"labelResourceProfile": "Resource Profile"', html)
        self.assertIn('/assets/execution-targets.js', html)
        self.assertIn('activeRunTarget = selectedExecutionTarget()', html)
        self.assertIn('execution_target: activeRunTarget', html)
        self.assertIn('resource_profile: selectedResourceProfile()', html)
        self.assertIn('id="work-dir-effective"', html)
        self.assertIn('"effectiveWorkDirLabel": "Using"', html)
        self.assertIn('"workDirLockedHint": "Locked to the actual run directory"', html)
        self.assertIn('function updateEffectiveWorkDirLabel()', html)
        self.assertIn('function setWorkDirLocked(isLocked)', html)
        self.assertIn('function builderWorkDirValue()', html)
        self.assertIn('function directoryFromPath(pathValue)', html)
        self.assertIn("const incomingRunDir = typeof event.data.run_dir === 'string'", html)
        self.assertIn('setWorkDirLocked(true);', html)
        self.assertIn("input.locked-input", html)
        self.assertIn('id="model-hamiltonian-section"', html)
        self.assertIn('id="open-model-builder"', html)
        self.assertIn('id="model-hamiltonian-input-file" type="hidden"', html)
        self.assertNotIn('Builder 输出 / Agent 输入文件', html)
        self.assertNotIn('Builder Output / Agent Input File', html)
        self.assertNotIn('id="model-hamiltonian-path-help"', html)
        self.assertNotIn('id="model-hamiltonian-path-preview"', html)
        self.assertNotIn('Current Run Directory', html)
        self.assertNotIn('当前运行目录', html)
        self.assertIn('id="model-hamiltonian-structure-preview"', html)
        self.assertIn('model-structure-preview', html)
        self.assertIn('id="molecular-structure-preview" class="molecule-preview"', html)
        self.assertIn('function parseMolecularAtomString(atomText)', html)
        self.assertIn('function renderMolecularStructurePreview(targetOrId, atomText, options = {})', html)
        self.assertIn('function updateMolecularStructurePreview()', html)
        self.assertIn("document.getElementById('atom').addEventListener('input', () => {", html)
        self.assertIn('clearMolecularStructureValidation();', html)
        self.assertIn('updateMolecularStructurePreview();', html)
        self.assertIn('class="model-toolbar"', html)
        self.assertIn('class="model-preview-section"', html)
        self.assertIn('model-structure-svg', html)
        self.assertNotIn('<div class="detail-panel">\n            <div class="section-header">\n              <h4 id="model-hamiltonian-preview-title">', html)
        self.assertIn('id="preview-model-hamiltonian"', html)
        self.assertIn('/api/model-hamiltonian-preview', html)
        self.assertIn('function previewModelHamiltonianStructure()', html)
        self.assertIn('function renderModelHamiltonianStructurePreview(preview)', html)
        self.assertNotIn('formatModelHamiltonianStructurePreview', html)
        self.assertNotIn('function updateModelHamiltonianPathPreview()', html)
        self.assertNotIn('function modelHamiltonianInputPath()', html)
        self.assertNotIn('model_hamiltonian_ui/generated/pyscf_model_hamiltonian_input.py', html)
        self.assertNotIn('/Downloads/pyscf_model_hamiltonian_input.py', html)
        self.assertIn('/model-hamiltonian-builder/', html)
        self.assertIn('DEFAULT_WORK_DIR', html)
        self.assertIn('function makeRunId()', html)
        self.assertIn('function beginTaskExecutionRun()', html)
        self.assertIn('const { runId, workDir } = beginTaskExecutionRun();', html)
        self.assertIn('work_dir: workDir', html)
        self.assertIn("calculationRole === 'active_space_probe'", html)
        self.assertIn("langText('Probe method', '探测方法')", html)
        self.assertIn('function handleBuilderMessage(event)', html)
        self.assertIn("pyscf-agent:model-hamiltonian-input-saved", html)
        self.assertIn("window.addEventListener('message', handleBuilderMessage);", html)
        self.assertNotIn('work_dir: effectiveWorkDir()', html)
        self.assertIn('run_id: runId', html)
        self.assertIn("target: 'agent'", html)
        self.assertIn("event.data.target && event.data.target !== 'agent'", html)
        self.assertIn('function openModelHamiltonianBuilder()', html)
        self.assertIn("window.name = 'pyscf-agent-web-ui';", html)
        self.assertIn("'pyscf-agent-model-builder'", html)
        self.assertNotIn("window.open(`/model-hamiltonian-builder/?${params.toString()}`, '_blank', 'noopener');", html)
        self.assertIn('id="advanced-parameters"', html)
        self.assertIn('id="charge" type="number" step="1" value="0"', html)
        self.assertIn('id="spin" type="number" step="1" min="0" value="0"', html)
        self.assertIn('id="restricted"', html)
        self.assertIn('<option value="auto" selected>Auto</option>', html)
        self.assertIn("charge: integerInputValue('charge', 0)", html)
        self.assertIn("spin: integerInputValue('spin', 0)", html)
        self.assertIn("payload.restricted = restricted === 'true';", html)
        self.assertIn("document.getElementById('restricted').value = taskSpec.restricted ? 'true' : 'false';", html)
        self.assertIn('id="model-solver"', html)
        model_solver_start = html.index('id="model-solver"')
        model_solver_end = html.index('</select>', model_solver_start)
        model_solver_html = html[model_solver_start:model_solver_end]
        self.assertIn('<option value="mp2">MP2</option>', model_solver_html)
        self.assertIn('<option value="ccsd">CCSD</option>', model_solver_html)
        self.assertIn('<option value="ccsd_t">CCSD(T)</option>', model_solver_html)
        self.assertNotIn('<option value="cisd">CISD</option>', model_solver_html)
        self.assertIn('<option value="fci" selected>Full CI</option>', model_solver_html)
        self.assertIn('function syncTaskFamilyControls()', html)
        self.assertIn('function collectModelHamiltonianFormData()', html)
        self.assertIn('function selectedOutputValues()', html)
        self.assertIn('const DEFAULT_MOLECULAR_OUTPUTS = ["energy", "homo_lumo", "dipole"];', html)
        self.assertIn('return DEFAULT_MOLECULAR_OUTPUTS.slice();', html)
        self.assertIn("task_type: 'model_hamiltonian'", html)
        self.assertIn("model_hamiltonian_input_file: document.getElementById('model-hamiltonian-input-file').value.trim()", html)
        self.assertIn("outputs: selectedOutputValues()", html)
        self.assertIn('id="molecular-output-group"', html)
        self.assertIn('id="model-output-group"', html)
        molecular_group_start = html.index('id="molecular-output-group"')
        molecular_group_end = html.index('</div>', molecular_group_start)
        molecular_group_html = html[molecular_group_start:molecular_group_end]
        self.assertNotIn('value="energy"', molecular_group_html)
        self.assertNotIn('value="homo_lumo"', molecular_group_html)
        self.assertNotIn('value="dipole"', molecular_group_html)
        model_group_start = html.index('id="model-output-group"')
        model_group_end = html.index('</div>', model_group_start)
        model_group_html = html[model_group_start:model_group_end]
        self.assertNotIn('value="energy"', model_group_html)
        self.assertIn('.output-group[data-output-family="model_hamiltonian"] > .checkbox-item:first-child { grid-column: 1 / -1; }', html)
        self.assertIn('<input type="checkbox" name="outputs" value="strong_correlation_diagnostics"', html)
        self.assertNotIn('<input type="checkbox" name="outputs" value="spin_correlation"', html)
        self.assertNotIn('<input type="checkbox" name="outputs" value="charge_correlation"', html)
        self.assertNotIn('<input type="checkbox" name="outputs" value="double_occupancy"', html)
        self.assertNotIn('<input type="checkbox" name="outputs" value="density"', html)
        self.assertNotIn('<input type="checkbox" name="outputs" value="gap"', html)
        self.assertNotIn('"spin_correlation": "Spin correlation"', html)
        self.assertNotIn('"charge_correlation": "Charge correlation"', html)
        self.assertNotIn('"density": "Density vector"', html)
        self.assertNotIn('"density": "密度向量"', html)
        self.assertIn('"strong_correlation_diagnostics": "Strong correlation diagnostics"', html)
        self.assertIn('id="strong-correlation-diagnostics-panel" class="detail-panel hidden"', html)
        self.assertNotIn('layout-wide-panel', html)
        self.assertIn('.result-table { width: 100%; border-collapse: collapse; table-layout: fixed; border-top: 2px solid #0f172a; border-bottom: 2px solid #0f172a;', html)
        self.assertIn('.result-table.compact tbody th { width: 22%; }', html)
        self.assertIn('.result-table.diagnostic-table tbody th:first-child { width: 34%; }', html)
        self.assertIn('.result-table.diagnostic-table tbody td:nth-child(2) { width: 66%; }', html)
        self.assertIn('.result-notes { margin: 0; padding-left: 1.25rem; color: #334155; }', html)
        self.assertIn('.result-note-sections { display: grid; gap: 0.8rem; }', html)
        self.assertIn('function formatDiagnosticValue(value)', html)
        self.assertIn('function appendDiagnosticRows(rows, label, value)', html)
        self.assertIn('function hasDiagnosticValue(item)', html)
        self.assertIn('function shouldShowDiagnosticTableRow(item)', html)
        self.assertIn("new Set(['mean_field_homo_lumo_gap', 'frontier_orbital_degeneracy', 'max_double_excitation_amplitude'])", html)
        self.assertIn('function shouldShowDiagnosticAnalysisNote(item)', html)
        self.assertIn("new Set(['reference_correlation_energy', 'solver_convergence'])", html)
        self.assertIn('function sanitizeDiagnosticSummary(text)', html)
        self.assertIn('function renderTableWithSections(id, headers, rows, sections, emptyText, className = \'\')', html)
        self.assertIn('function renderStrongCorrelationDiagnostics(results)', html)
        self.assertIn('id="active-space-audit-panel" class="detail-panel hidden"', html)
        self.assertIn('function renderActiveSpaceAudit(results)', html)
        self.assertIn("renderActiveSpaceAudit(payload.structured_results);", html)
        self.assertIn('id="approval-active-space-review" class="active-space-approval-review hidden"', html)
        self.assertIn('class="active-space-review-grid"', html)
        self.assertIn('class="active-space-orbital-table"', html)
        self.assertIn('id="approval-draft-details" class="approval-draft-details" open', html)
        self.assertIn('id="approval-draft-summary" class="hidden"', html)
        self.assertIn('function activeSpaceApprovalReview(activeSpace, contract)', html)
        self.assertIn('function renderActiveSpaceApprovalReview(review)', html)
        self.assertIn('function buildActiveSpaceApprovalFromResult(payload)', html)
        self.assertIn("payload.approval.type === 'active_space'", html)
        self.assertIn('explicitApproval.active_space_contract', html)
        self.assertIn("item.code === 'active_space_not_approved'", html)
        self.assertIn("approval.next_approval.type === 'active_space'", html)
        self.assertIn("source = 'blocked_active_space_contract'", html)
        self.assertIn("pendingApproval.target_method || 'casscf'", html)
        self.assertIn('pendingApproval.target_solver', html)
        self.assertIn("target_solver: targetsCas ? activeSpaceSolver : null", html)
        self.assertIn('if (targetsCas)', html)
        self.assertIn("fetch('/api/active-space-probe'", html)
        self.assertNotIn('taskSpec.method = \'mp2\';', html)
        self.assertIn("[langText('Target solver', '目标求解器')", html)
        self.assertIn('function resultsSolverName(results)', html)
        self.assertIn("langText('Solver', '求解器')", html)
        self.assertIn('approvalActiveSpaceDirectSystemMessage', html)
        self.assertIn('approvalActiveSpacePreparedSource', html)
        self.assertIn('approvalActiveSpaceDirectSource', html)
        self.assertIn('active_space_review: activeSpaceApprovalReview(activeSpace, activeSpaceDraft)', html)
        self.assertIn('function approvePendingActiveSpace()', html)
        self.assertIn('taskSpec.runtime = { ...pendingApproval.runtime_contract };', html)
        self.assertIn('runtime_contract: runtimeContract', html)
        self.assertIn('probe_reference_status: probeReferenceStatus', html)
        self.assertIn("langText('Initial reference converged', '初始参考态收敛')", html)
        self.assertIn('function approvePendingApproval()', html)
        self.assertIn('function cancelPendingApproval()', html)
        self.assertIn('function isSpinResolvedOrbitalIndices(value)', html)
        self.assertIn('function activeOrbitalIndicesToText(value)', html)
        self.assertIn('function normalizeApprovalOrbitalIndices(value)', html)
        self.assertIn('unrestricted: alpha:4,5; beta:4,5', html)
        self.assertIn('alpha:4,5; beta:4,5', html)
        self.assertIn('function casRestrictedValueForActiveSpace(contract)', html)
        self.assertNotIn("if (selectedReference === 'false')", html)
        self.assertNotIn("document.getElementById('active-space-probe-strategy')", html)
        self.assertIn('target_solver_options: targetSolverOptions', html)
        self.assertIn("document.getElementById('restricted').value = taskSpec.restricted ? 'true' : 'false';", html)
        self.assertIn("renderApprovalPanel(buildTaskApprovalFromResult(payload));", html)
        self.assertIn('function buildCorrelatedSubspaceApprovalFromResult(payload)', html)
        self.assertIn('function approvePendingCorrelatedSubspace()', html)
        self.assertIn("applyPendingApprovalLifecycle('approve', 'correlated_subspace')", html)
        self.assertIn('id="periodic-correlation-treatment"', html)
        self.assertIn('<option value="hf_dmft">Hartree-Fock plus DMFT</option>', html)
        self.assertIn('<option value="gw">Periodic G0W0</option>', html)
        self.assertIn('<option value="gw_dmft">GW plus DMFT</option>', html)
        self.assertIn('id="periodic-dmft-nbath" type="number" min="2"', html)
        self.assertIn("Math.max(2, integerInputValue('periodic-dmft-nbath', 4))", html)
        self.assertIn("const referenceLabel = isGwDmft ? 'DFT reference converged' : 'HF reference converged';", html)
        self.assertIn("appendRow(`${isGwDmft ? 'GW+DMFT' : 'HF+DMFT'} converged`", html)
        self.assertIn("appendRow('GW status'", html)
        self.assertIn("'DMFT total energy'", html)
        self.assertNotIn('taskSpec.restricted = true;', html)
        self.assertIn('"approvalActiveSpaceTitle": "Active Space To Review"', html)
        self.assertIn('"approvalActiveSpaceSystemMessage": "Automatic active-space selection generated a candidate. Review the structured proposal below."', html)
        self.assertIn('"approvalActiveSpaceJsonEditor": "Advanced JSON Edit"', html)
        self.assertNotIn('function activeSpaceApprovalEvidence(activeSpace)', html)
        self.assertNotIn('id="approve-active-space-from-audit"', html)
        self.assertNotIn('id="edit-active-space-from-audit"', html)
        self.assertNotIn('id="run-casscf-from-audit"', html)
        self.assertNotIn('function runCasscfFromApprovedActiveSpace()', html)
        self.assertNotIn('active-space-audit-actions', html)
        self.assertNotIn("${langText('orbitals', '轨道')}=", html)
        self.assertNotIn("${langText('mode', '模式')}=", html)
        self.assertIn("t('modelHamiltonianPrepared')", html)
        self.assertNotIn('Reads a local PySCF input file generated by the builder UI.', html)
        self.assertNotIn('暂不支持 Holstein-Hubbard', html)
        self.assertNotIn('id="model-hamiltonian-hint"', html)
        self.assertIn('待确认结构草案', html)
        self.assertIn('确认计算', html)
        self.assertIn('<div class="conversation-request">', html)
        self.assertIn('.conversation-request { display: grid; gap: 0.45rem; margin-top: 0.9rem; }', html)
        self.assertNotIn('.conversation-request { display: grid; gap: 0.45rem; margin-top: 0.9rem; padding-top: 0.9rem; border-top:', html)
        self.assertLess(html.index('<div id="conversation" class="conversation">'), html.index('<div id="approval-panel" class="approval-panel">'))
        self.assertLess(html.index('<div id="approval-panel" class="approval-panel">'), html.index('<div class="conversation-request">'))
        self.assertLess(html.index('<div class="conversation-request">'), html.index('<div class="conversation-action-bar">'))
        self.assertLess(html.index('<div class="conversation-action-bar">'), html.index('<div class="conversation-actions">'))
        self.assertLess(html.index('<div class="conversation-actions">'), html.index('<div id="compute-confirm-panel" class="compute-confirm-panel">'))
        self.assertLess(html.index('<div id="compute-confirm-panel" class="compute-confirm-panel">'), html.index('<div class="conversation-secondary-actions">'))
        self.assertIn('id="active-space-section" class="active-space-details"', html)
        self.assertIn('<summary id="active-space-section-title">Active Space</summary>', html)
        self.assertIn('id="active-space-summary" class="active-space-summary"', html)
        self.assertIn('class="active-space-top-row"', html)
        self.assertIn('id="screen-active-space" type="button" class="secondary"', html)
        self.assertIn('"activeSpaceScreenButton": "Auto Select"', html)
        self.assertNotIn('id="active-space-probe-strategy"', html)
        self.assertNotIn('labelActiveSpaceProbeStrategy', html)
        self.assertNotIn('active_space_probe_strategy_options', html)
        self.assertNotIn('Screen Active Space', html)
        self.assertIn('id="active-space-contract-title"', html)
        self.assertIn('"labelNcas": "Active Orbital Count"', html)
        self.assertNotIn('"labelNcas": "Active Orbitals"', html)
        self.assertIn('id="post-cas-controls" class="post-cas-controls"', html)
        self.assertNotIn('id="active-space-manual-editor"', html)
        self.assertNotIn('id="post-cas-section" class="inline-settings"', html)
        self.assertIn('id="active-space-solver"', html)
        self.assertIn('<option value="block2_dmrg">block2 DMRG</option>', html)
        self.assertIn('id="model-root-control"', html)
        self.assertIn('id="model-nroots" type="number" min="1" step="1" value="1"', html)
        self.assertIn('function syncModelSolverControls()', html)
        self.assertIn("solverName === 'fci' || solverName === 'block2_dmrg'", html)
        self.assertIn('solver = { name: solverName, options: { nroots } };', html)
        self.assertIn("nroots > 1 && !outputs.includes('excited_states')", html)
        self.assertIn("output !== 'excited_states'", html)
        self.assertIn('excitedStatesOutput.disabled = !supportsRoots;', html)
        self.assertIn('if (!supportsRoots) excitedStatesOutput.checked = false;', html)
        self.assertIn('id="model-dmet-controls" class="form-section stack hidden"', html)
        self.assertIn('id="model-dmet-execution-mode"', html)
        self.assertIn('<option value="">Automatic</option>', html)
        self.assertIn('<option value="translational">Translational symmetry</option>', html)
        self.assertIn('<option value="finite_graph">Finite graph</option>', html)
        self.assertIn('<option value="primitive_cell">Primitive cell</option>', html)
        self.assertNotIn('Auto (symmetry-aware)', html)
        self.assertNotIn('Auto (Unrestricted)', html)
        self.assertIn('id="model-dmet-reference-density"', html)
        self.assertIn('<option value="pm" selected>0 (Paramagnetic)</option>', html)
        self.assertIn('<option value="af">Antiferromagnetic</option>', html)
        self.assertIn('<option value="fm">Ferromagnetic</option>', html)
        self.assertNotIn('Initializes only the UHF spin-density seed. The auxiliary DMET correlation potential always starts from zero.', html)
        self.assertIn('<select id="model-dmet-interacting-bath">', html)
        self.assertIn('if (executionMode) options.execution_mode = executionMode;', html)
        self.assertIn('if (fragmentMode) options.fragment_definition = fragmentMode;', html)
        self.assertNotIn('execution_mode: executionMode,', html)
        self.assertNotIn('fragment_definition: fragmentMode,', html)
        self.assertIn('id="model-dmet-spin-sector" class="dmet-spin-sector"', html)
        self.assertIn('id="model-dmet-validation" class="field-validation"', html)
        self.assertIn('function renderDmetSpinSector()', html)
        self.assertIn('function validateDmetModelControls()', html)
        self.assertIn("['libDMET Sz', sector.libdmet_sz]", html)
        self.assertIn("['physical Sz', sector.physical_sz]", html)
        self.assertIn('solver: document.getElementById(\'model-solver\').value === \'dmet\'', html)
        self.assertIn('const dmetFormError = await validateDmetModelControls();', html)
        self.assertIn("name: 'dmet'", html)
        self.assertIn('options: collectDmetSolverOptions()', html)
        self.assertIn('density_tolerance:', html)
        self.assertIn('<strong>1RDM Tolerance</strong>', html)
        self.assertIn("'DMET convergence criteria'", html)
        self.assertIn("'Final DMET changes'", html)
        self.assertIn('<option value="block2_dmrg">block2 DMRG</option>', html)
        self.assertIn('id="model-dmet-block2-preset"', html)
        self.assertIn('id="model-dmet-block2-ordering"', html)
        self.assertIn("impurity_solver_options: impuritySolver === 'block2_dmrg'", html)
        self.assertIn("appendRow('DMRG impurity convergence'", html)
        self.assertIn("'DMRG final discarded weight'", html)
        self.assertIn("appendRow('DMRG MPS continuations'", html)
        self.assertIn("modelNroots: document.getElementById('model-nroots').value", html)
        self.assertIn("document.getElementById('model-nroots').value = form.modelNroots || '1';", html)
        self.assertIn('id="state-energies-panel" class="detail-panel hidden"', html)
        self.assertIn('function renderTargetedStateEnergies(results)', html)
        self.assertIn('id="state-target-controls" class="active-space-details hidden"', html)
        self.assertIn('id="state-target-nroots" type="number" step="1" min="1" value="1"', html)
        self.assertIn('id="state-average-weights" type="text"', html)
        self.assertIn("method === 'casscf' && stateTargetNroots > 1", html)
        self.assertIn('target_solver_options: targetsCas ? stateTargetOptions : {}', html)
        self.assertIn('activeSpaceContract.target_solver_options || {}', html)
        self.assertIn("['Number of roots', casscf.nroots]", html)
        self.assertIn("['State-average weights', isStateAveraged && Array.isArray(dmrg.state_average_weights)", html)
        self.assertIn('id="localization-scope"', html)
        self.assertIn('<option value="active_space">block2 active space</option>', html)
        self.assertIn('"localizationScopeActiveSpace": "block2 active space"', html)
        self.assertIn('id="orbital-ordering"', html)
        self.assertIn('<option value="fiedler">Fiedler</option>', html)
        self.assertIn('id="manual-orbital-order"', html)
        self.assertIn('localization_scope: localizationScope', html)
        self.assertIn('orbital_ordering: orbitalOrdering', html)
        self.assertIn("orbital_order: orbitalOrdering === 'manual' ? orbitalOrder : []", html)
        self.assertIn('function syncOrbitalProcessingControls()', html)
        self.assertIn("const targetMethod = pendingApproval.target_method || 'casscf';", html)
        self.assertIn('id="block2-analysis-panel"', html)
        self.assertIn('id="block2-state-section" class="block2-state-section hidden"', html)
        self.assertIn('renderBlock2Analysis', html)
        self.assertIn("['Planned bond-dimension cap', bondPlan.exact_bond_dimension_cap]", html)
        self.assertIn('bondPlan.effective_bond_dimensions.join', html)
        self.assertIn('casResult.orbital_provenance', html)
        self.assertIn("['Final active orbitals', provenance.output_basis ? block2OrbitalBasisLabel(provenance.output_basis) : null]", html)
        self.assertIn("['Executed permutation', isIdentityPermutation(permutation) ? null : compactOrbitalPermutation(permutation)]", html)
        self.assertIn('Unavailable because the block2 NPDM interface failed', html)
        self.assertNotIn('Matrix is stored in the block2 array artifact', html)
        self.assertIn('id="block2-entanglement-grid" class="block2-analysis-grid hidden"', html)
        self.assertIn('id="block2-entanglement-note" class="block2-entanglement-note hidden"', html)
        self.assertIn("['Root', 'Total energy (a.u.)', 'Excitation energy (a.u.)']", html)
        self.assertIn("setBlock2SectionVisibility('block2-entropy-section', showEntropy);", html)
        self.assertIn("setBlock2SectionVisibility('block2-state-section', showStateEnergies);", html)
        self.assertIn("entanglementGrid.classList.toggle('single-column', visibleEntanglementSections === 1);", html)
        self.assertIn('.block2-analysis-grid.single-column { grid-template-columns: minmax(0, 42rem); }', html)
        self.assertIn('.block2-bar-fill { display: block;', html)
        self.assertIn('Entanglement diagnostics were not requested for this run.', html)
        self.assertIn('.result-table.block2-state-table', html)
        self.assertIn('id="sc-nevpt2-enabled" type="checkbox"', html)
        self.assertIn('id="sc-nevpt2-root" type="number" step="1" min="0" max="0" value="0"', html)
        self.assertIn('root: 0,', html)
        self.assertNotIn("root: integerInputValue('sc-nevpt2-root', 0)", html)
        self.assertIn('function syncPostCasControls()', html)
        self.assertIn("const supportedReference = (method === 'casci' || method === 'casscf') && !unrestricted && activeSpaceSolver !== 'block2_dmrg';", html)
        self.assertIn('unrestricted CAS is not supported', html)
        self.assertIn("document.getElementById('restricted').addEventListener('change', syncPostCasControls);", html)
        self.assertIn('post_cas: {', html)
        self.assertIn('sc_nevpt2: {', html)
        self.assertIn('await executePreparedRequest(JSON.stringify(prepared.probe_request));', html)
        self.assertNotIn("taskSpec.post_cas = { sc_nevpt2: { enabled: false, root: 0, density_fit: true } };", html)
        self.assertIn('payload.structured_results.post_cas_results.sc_nevpt2', html)
        self.assertIn("appendRow('SC-NEVPT2 correction'", html)
        self.assertIn("langText('Final energy', '最终能量')", html)
        self.assertIn('function screenActiveSpace()', html)
        self.assertIn('.active-space-details { border: 0; border-top: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0;', html)
        self.assertIn('.active-space-details summary::after { content: "+";', html)
        self.assertNotIn('id="label-outputs"', html)
        self.assertNotIn('#label-outputs', html)
        self.assertNotIn('Analysis Outputs', html)
        self.assertIn('.output-group[data-output-family="model_hamiltonian"] > .checkbox-item:first-child { grid-column: 1 / -1; }', html)
        self.assertIn('result-table-block', html)
        self.assertIn('.result-notes { margin: 0; padding-left: 1.25rem; color: #334155; }', html)
        self.assertIn('renderTableWithNotes(\'summary\', [langText(\'Item\', \'项目\'), langText(\'Value\', \'数值\')], rows, notes, t(\'summaryEmpty\'), \'compact\');', html)
        self.assertIn('"diagnosticDataAnalysisTitle": "Data Analysis"', html)
        self.assertIn('"diagnosticLevelTitle": "Correlation Level"', html)
        self.assertIn('"diagnosticMethodTitle": "Method Recommendation"', html)
        self.assertIn('"activeSpaceAuditTitle": "Active Space Audit"', html)
        self.assertIn("renderTableWithSections('strong-correlation-diagnostics', ['Item', 'Value'], rows, [", html)
        self.assertIn("langText('Correlation evidence', '电子关联证据')", html)
        self.assertIn("langText('Solver stress', '求解器风险')", html)
        self.assertIn("langText('State and parameter context', '态与参数特征')", html)
        self.assertIn('活性轨道数', html)
        self.assertIn('活性电子数', html)
        self.assertNotIn('活性轨道数 (ncas)', html)
        self.assertNotIn('活性电子数 (nelecas)', html)
        self.assertNotIn('id="continue-editing"', html)
        self.assertIn('准备请求', html)
        self.assertIn('Prepare Request', html)
        self.assertIn('PySCF 计算助手', html)
        self.assertIn('将自然语言整理为可审查的 PySCF 请求，并通过预定义 workflow 执行计算。', html)
        self.assertIn('id="study-agent-link"', html)
        self.assertIn('href="/computational-study/"', html)
        self.assertIn('"openStudyAgent": "Planner Agent"', html)
        self.assertIn('font-size: 0.92rem', html)
        self.assertIn("document.getElementById('study-agent-link').textContent = t('openStudyAgent');", html)
        self.assertIn('function invalidatePendingExecution()', html)
        self.assertIn('prepared.execution_request_text || prepared.request_text', html)
        self.assertNotIn('await executePreparedRequest(prepared.request_text);', html)
        self.assertIn('approval.probe_request', html)
        self.assertIn('approvedProbeRequest', html)
        self.assertIn('id="confirm-compute" type="button" disabled', html)
        self.assertNotIn('id="compute-confirm-hint"', html)
        self.assertNotIn('The request is ready. Review the structure and parameters, then start the PySCF calculation.', html)
        self.assertNotIn('Prepare the request first. Calculation will be enabled when ready.', html)
        self.assertIn('Analyze Results', html)
        self.assertIn('未配置 LLM，无法分析结果', html)
        self.assertNotIn("window.localStorage.setItem('pyscf-agent-ui-language', currentLanguage);", html)
        self.assertNotIn('if (LANGUAGE_SWITCH_ENABLED)', html)
        self.assertNotIn("languageToggle.addEventListener('click'", html)
        self.assertIn("window.localStorage.removeItem('pyscf-agent-ui-language');", html)
        self.assertIn('Analyze Results', html)
        self.assertIn('llmResultAnalysisAvailable', html)
        self.assertIn('canAnalyzeCurrentResult', html)
        self.assertIn('approvePendingStructure', html)
        self.assertIn("document.getElementById('approve-structure').addEventListener('click', approvePendingApproval);", html)
        self.assertIn('const approval = pendingApproval;', html)
        self.assertIn('approval.can_run_immediately', html)
        self.assertIn('>Auto Select</button>', html)
        self.assertIn('>AVAS AO/fragment targets</strong>', html)
        self.assertIn('placeholder="e.g. Fe 3d or atom:0,1"', html)
        self.assertIn('cancelPendingStructure', html)
        self.assertIn("document.getElementById('cancel-structure').addEventListener('click', cancelPendingApproval);", html)
        self.assertIn('confirmCompute', html)
        self.assertNotIn('function continueEditing()', html)
        self.assertIn('analyzeCurrentResult', html)
        self.assertIn('/api/analyze-result', html)
        self.assertIn('approved_structured_request', html)
        self.assertIn("item.kind === 'intent' || item.content === '已解析用户请求'", html)
        self.assertIn("item.content === 'Parsed user request'", html)
        self.assertIn('"runStarted": "The task has started running."', html)
        self.assertIn('"statusCalculating": "Calculating"', html)
        self.assertIn('"runCancelled": "The calculation was stopped by the user."', html)
        self.assertIn("postCalculationLifecycle('/api/run-submit'", html)
        self.assertIn("postCalculationLifecycle('/api/run-status'", html)
        self.assertIn("postCalculationLifecycle('/api/run-collect'", html)
        self.assertIn("postCalculationLifecycle('/api/run-cancel'", html)
        self.assertIn("clearButton.textContent = isStopping ? t('stopping') : t('stop');", html)
        self.assertIn("updateActiveTaskSessionStatus('cancelled');", html)
        self.assertNotIn("fetch('/api/run',", html)
        self.assertIn('"runCompleted": "The task completed successfully."', html)
        self.assertIn('"runEnded": "The task has finished."', html)
        self.assertIn('"analyzeEmptyResult": "Analysis finished, but the returned content was empty."', html)
        self.assertIn('"summaryDefaultsLabel": "Defaults"', html)
        self.assertIn('"summaryPrecisionLabel": "Precision Note"', html)
        self.assertNotIn('function buildRequestSummary(', html)
        self.assertNotIn('请求来源：${', html)
        self.assertNotIn('LLM 状态：${', html)
        self.assertNotIn('已提取字段：${', html)
        self.assertIn("blocks.push(`[raw_stderr]\\n${payload.raw_stderr}`);", html)
        self.assertIn("t('noStderrAnalysis')", html)
        self.assertIn('renderTableWithNotes(\'summary\', [langText(\'Item\', \'项目\'), langText(\'Value\', \'数值\')], rows, notes, t(\'summaryEmpty\'), \'compact\');', html)
        self.assertIn("renderTableWithSections('strong-correlation-diagnostics', ['Item', 'Value'], rows, [", html)

    def test_periodic_task_controls_and_structured_request_are_rendered(self):
        html = assistant_ui_source(web_ui.build_index_html())

        self.assertIn('<option value="periodic" data-label-key="taskFamilyPeriodic">', html)
        self.assertIn('id="periodic-section"', html)
        self.assertIn('id="periodic-file" type="file"', html)
        self.assertNotIn('id="periodic-file" type="file" accept=', html)
        self.assertIn('id="periodic-structure-text"', html)
        self.assertIn('id="periodic-basis"', html)
        self.assertIn('<option value="gth-szv-molopt-sr" selected>GTH-SZV-MOLOPT-SR</option>', html)
        self.assertIn('id="periodic-pseudo"', html)
        self.assertIn('<option value="gth-pade">GTH-PADE (H-Rn)</option>', html)
        self.assertIn('<option value="gth-pbe" selected>GTH-PBE (H-Rn)</option>', html)
        self.assertIn('id="periodic-method"', html)
        self.assertIn('id="periodic-xc"', html)
        self.assertIn('id="periodic-kmesh-x"', html)
        self.assertIn('id="periodic-kmesh-y"', html)
        self.assertIn('id="periodic-kmesh-z"', html)
        self.assertIn('id="periodic-kpoint-scheme"', html)
        self.assertIn('id="periodic-band-path-mode"', html)
        self.assertIn('<option value="auto" selected data-label-key="periodicBandPathModeAuto">', html)
        self.assertIn('<option value="seekpath" data-label-key="periodicBandPathModeSeekpath">', html)
        self.assertIn('id="periodic-band-path"', html)
        self.assertIn('id="periodic-band-special-points"', html)
        self.assertIn('id="periodic-band-path-npoints"', html)
        self.assertIn('id="periodic-band-path-reference-distance"', html)
        self.assertIn('id="periodic-band-path-symprec"', html)
        self.assertIn('<option value="gamma_centered" selected>Gamma-centered</option>', html)
        self.assertIn('id="periodic-numerics-section" class="active-space-details"', html)
        self.assertIn('id="periodic-precision"', html)
        self.assertIn('id="periodic-ke-cutoff"', html)
        self.assertIn('id="periodic-fft-mesh-x"', html)
        self.assertIn('id="periodic-density-fitting"', html)
        self.assertIn('<option value="fft" selected>FFTDF</option>', html)
        self.assertIn('id="periodic-df-auxbasis"', html)
        self.assertIn('id="periodic-exxdiv"', html)
        self.assertIn('<option value="ewald" selected>Ewald</option>', html)
        self.assertIn('id="periodic-smearing"', html)
        self.assertIn('id="periodic-smearing-sigma"', html)
        self.assertIn('id="periodic-smearing-fix-spin"', html)
        self.assertIn('id="periodic-kpoint-shift-x"', html)
        self.assertIn('function renderPeriodicStructurePreview(preview)', html)
        self.assertIn('function previewPeriodicStructure()', html)
        self.assertIn("fetch('/api/periodic-structure-preview'", html)
        self.assertIn('function collectPeriodicFormData()', html)
        self.assertIn('function validatePeriodicFormControls()', html)
        self.assertIn('function syncPeriodicNumericalControls()', html)
        self.assertIn('function syncPeriodicBandPathControls(seedFromPreview = false)', html)
        self.assertIn('function parsePeriodicBandSpecialPoints(value)', html)
        self.assertIn("task_type: 'periodic'", html)
        self.assertIn("density_fitting_method: densityFittingMethod", html)
        self.assertIn("smearing_method: smearingMethod", html)
        self.assertIn("kpoint_scheme: document.getElementById('periodic-kpoint-scheme').value", html)
        self.assertIn('band_path_mode: bandPathMode', html)
        self.assertIn(
            "band_path: bandPathMode === 'custom' || bandPathMode === 'explicit' ? bandPath : null",
            html,
        )
        self.assertIn("band_path_special_points: bandPathMode === 'explicit' ? explicitSpecialPoints : {}", html)
        self.assertIn("band_path_npoints: integerInputValue('periodic-band-path-npoints', 80)", html)
        self.assertIn("band_path_reference_distance: numericInputValue('periodic-band-path-reference-distance', 0.025)", html)
        self.assertIn("band_path_symprec: numericInputValue('periodic-band-path-symprec', 1e-5)", html)
        self.assertIn("const seekpathMode = mode === 'seekpath'", html)
        self.assertIn("preview.seekpath_preview", html)
        self.assertIn("seekpath_symprec: numericInputValue('periodic-band-path-symprec', 1e-5)", html)
        self.assertIn('seekpathPreview.explicit_point_count', html)
        self.assertIn('value="band_structure"', html)
        self.assertIn('High-symmetry band structure', html)
        self.assertIn('outputs: selectedOutputValues()', html)
        self.assertIn("if (task_spec.task_type === 'periodic')", html)
        self.assertIn("renderComputeConfirmPanel(t('computeReady'), preparedRequestText);", html)
        self.assertIn("langText('Energy per cell', '每晶胞总能')", html)
        self.assertIn("langText('Mean-field band gap', '平均场带隙')", html)
        self.assertIn("taskType === 'periodic' ? payload.structured_results.band_gap", html)
        self.assertIn("langText('Direct band gap', '直接带隙')", html)
        self.assertIn("langText('Fermi level', '费米能级')", html)
        self.assertIn('pyscf_get_fermi_smearing_chemical_potential', html)

if __name__ == '__main__':
    unittest.main()
