from __future__ import annotations

from pyscf_agent.executors.commands import run_bounded, command_timeout, DEPLOYMENT_TIMEOUT_SECONDS

import base64
import configparser
import io
import json
import os
import re
import shlex
import subprocess
import tarfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Dict, Optional, Sequence

from ..executors.remote_config import load_remote_profile, resolve_remote_config_path
from ..executors.ssh_slurm import SshSlurmExecutor
from ..runtime_identity import (
    assert_source_matches_identity,
    build_runtime_identity,
    source_files,
)


RUNTIME_BINDING_SCHEMA = 'pyscf-agent.runtime-binding.v1'


def _safe_id(value: str, name: str) -> str:
    normalized = re.sub(r'[^a-z0-9._-]+', '-', str(value or '').strip().lower()).strip('-._')
    if not normalized:
        raise ValueError('{0} must contain letters or numbers'.format(name))
    return normalized


def _timestamp_id() -> str:
    return datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%SZ')


def _source_archive(source_root: Path, files: Sequence[Path]) -> bytes:
    stream = io.BytesIO()
    with tarfile.open(fileobj=stream, mode='w:gz') as archive:
        for relative in files:
            archive.add(
                str(source_root / relative),
                arcname=relative.as_posix(),
                recursive=False,
            )
    return stream.getvalue()


def _default_ssh_runner(args: Sequence[str], payload: bytes) -> subprocess.CompletedProcess:
    return run_bounded(
        list(args),
        input=payload,
        timeout=DEPLOYMENT_TIMEOUT_SECONDS,
        capture_output=True,
        check=False,
    )


def _run_ssh(
    ssh_base: Sequence[str],
    command: str,
    *,
    payload: bytes = b'',
    runner: Callable[[Sequence[str], bytes], Any],
) -> str:
    try:
        result = runner([*ssh_base, command], payload)
    except subprocess.TimeoutExpired as exc:
        raise command_timeout('Remote deployment', exc) from exc
    return_code = int(getattr(result, 'returncode', 0))
    raw_stdout = getattr(result, 'stdout', b'') or b''
    raw_stderr = getattr(result, 'stderr', b'') or b''
    stdout = (
        raw_stdout.decode('utf-8', 'replace')
        if isinstance(raw_stdout, bytes)
        else str(raw_stdout)
    ).strip()
    stderr = (
        raw_stderr.decode('utf-8', 'replace')
        if isinstance(raw_stderr, bytes)
        else str(raw_stderr)
    ).strip()
    if return_code:
        raise RuntimeError(
            'Remote deployment command failed with code {0}: {1}'.format(
                return_code,
                stderr or stdout or 'no output',
            )
        )
    return stdout


def _write_private_config(
    *,
    source_config: Path,
    source_profile: str,
    target_config: Path,
    target_profile: str,
    local_source_root: Path,
    identity_path: Path,
    remote_result: Dict[str, Any],
    deployment_base_python: str,
    deployment_base_slurm_profile: str,
) -> None:
    source_parser = configparser.ConfigParser(interpolation=None)
    source_parser.read(str(source_config), encoding='utf-8')
    source_section = 'remote:{0}'.format(source_profile)
    if not source_parser.has_section(source_section):
        raise ValueError('Source remote profile was not found: {0}'.format(source_profile))
    values = dict(source_parser.items(source_section, raw=True))
    values.update({
        'remote_python': str(remote_result['python_wrapper']),
        'remote_slurm_profile': str(remote_result['server_profile']),
        'runtime_identity_file': str(identity_path),
        'require_runtime_match': 'true',
        'local_source_root': str(local_source_root),
        'deployment_base_python': deployment_base_python,
        'deployment_base_slurm_profile': deployment_base_slurm_profile,
    })
    parser = configparser.ConfigParser(interpolation=None)
    parser['remote:{0}'.format(target_profile)] = values
    target_config.parent.mkdir(parents=True, exist_ok=True)
    temporary = target_config.with_name(target_config.name + '.tmp')
    with temporary.open('w', encoding='utf-8') as handle:
        handle.write(
            '# Private per-worktree remote binding. Generated by deploy-remote; do not commit.\n\n'
        )
        parser.write(handle)
    temporary.chmod(0o600)
    os.replace(str(temporary), str(target_config))


def _deployment_base_python(
    source: Any,
    ssh_base: Sequence[str],
    *,
    runner: Callable[[Sequence[str], bytes], Any],
) -> str:
    """Return the real interpreter, never a prior release wrapper."""

    configured = str(source.deployment_base_python or '').strip()
    if configured:
        return configured
    if not source.require_runtime_match:
        return source.remote_python
    output = _run_ssh(
        ssh_base,
        shlex.join((
            source.remote_python,
            '-c',
            'import sys; print(sys.executable)',
        )),
        runner=runner,
    )
    resolved = output.splitlines()[-1].strip() if output else ''
    if not resolved:
        raise RuntimeError(
            'Could not resolve the base Python interpreter through the existing '
            'worktree release wrapper'
        )
    return resolved


def deploy_worktree_remote(
    *,
    source_root: str,
    environment_id: str,
    source_profile: str,
    source_remote_config: Optional[str] = None,
    target_remote_config: Optional[str] = None,
    target_profile: str = 'amarel',
    base_server_profile: Optional[str] = None,
    server_profile: Optional[str] = None,
    release_id: Optional[str] = None,
    ssh_runner: Callable[[Sequence[str], bytes], Any] = _default_ssh_runner,
    verify: bool = True,
) -> Dict[str, Any]:
    """Deploy one local worktree to an immutable, matching remote release."""

    root = Path(source_root).expanduser().resolve()
    normalized_environment = _safe_id(environment_id, 'environment_id')
    normalized_target = _safe_id(target_profile, 'target_profile')
    source_config = resolve_remote_config_path(source_remote_config)
    source = load_remote_profile(source_profile, str(source_config))
    base_profile = _safe_id(
        base_server_profile
        or source.deployment_base_slurm_profile
        or (
            source.profile_id
            if source.require_runtime_match
            else source.remote_slurm_profile or source.profile_id
        ),
        'base_server_profile',
    )
    selected_server_profile = _safe_id(
        server_profile or '{0}-{1}'.format(source.profile_id, normalized_environment),
        'server_profile',
    )
    files = source_files(root)
    provisional = build_runtime_identity(
        root,
        environment_id=normalized_environment,
        release_id='pending',
        files=files,
    )
    selected_release_id = _safe_id(
        release_id
        or '{0}-{1}-{2}'.format(
            normalized_environment,
            _timestamp_id(),
            provisional.source_fingerprint.rsplit(':', 1)[-1][:10],
        ),
        'release_id',
    )
    identity = build_runtime_identity(
        root,
        environment_id=normalized_environment,
        release_id=selected_release_id,
        files=files,
        created_at=provisional.created_at,
    )
    archive = _source_archive(root, files)
    assert_source_matches_identity(identity, root)

    executor = SshSlurmExecutor(source)
    ssh_base = executor._ssh_command('capabilities')[:-1]
    base_python = _deployment_base_python(
        source,
        ssh_base,
        runner=ssh_runner,
    )
    remote_relative = 'pyscf-agent-releases/{0}'.format(selected_release_id)
    upload_command = (
        'set -e; release="$HOME/{0}"; test ! -e "$release"; '
        'mkdir -p "$release/source"; tar -xzf - -C "$release/source"; '
        'test -f "$release/source/pyproject.toml"'
    ).format(remote_relative)
    _run_ssh(
        ssh_base,
        upload_command,
        payload=archive,
        runner=ssh_runner,
    )

    encoded_identity = base64.b64encode(
        json.dumps(identity.to_dict(), ensure_ascii=False).encode('utf-8')
    ).decode('ascii')
    remote_release = '"$HOME/{0}"'.format(remote_relative)
    configure_command = ' '.join((
        'PYTHONPATH={0}/source'.format(remote_release),
        shlex.quote(source.remote_python),
        '-m',
        'pyscf_agent.remote.deployment_server',
        '--server-config',
        shlex.quote(source.remote_slurm_config),
        '--base-profile',
        shlex.quote(base_profile),
        '--server-profile',
        shlex.quote(selected_server_profile),
        '--environment-id',
        shlex.quote(normalized_environment),
        '--release-root',
        remote_release,
        '--base-python',
        shlex.quote(base_python),
        '--identity-base64',
        shlex.quote(encoded_identity),
    ))
    output = _run_ssh(ssh_base, configure_command, runner=ssh_runner)
    try:
        remote_result = json.loads(output.splitlines()[-1])
    except (IndexError, json.JSONDecodeError) as exc:
        raise RuntimeError('Remote deployment did not return a release manifest') from exc
    if not isinstance(remote_result, dict):
        raise RuntimeError('Remote release manifest must be a dictionary')

    local_config = Path(
        target_remote_config or root / '.pyscf-agent' / 'remote.ini'
    ).expanduser().resolve()
    identity_path = local_config.parent / 'runtime-identity.json'
    identity_path.parent.mkdir(parents=True, exist_ok=True)
    identity_path.write_text(
        json.dumps(identity.to_dict(), ensure_ascii=False, indent=2) + '\n',
        encoding='utf-8',
    )
    identity_path.chmod(0o600)
    _write_private_config(
        source_config=source_config,
        source_profile=source_profile,
        target_config=local_config,
        target_profile=normalized_target,
        local_source_root=root,
        identity_path=identity_path,
        remote_result=remote_result,
        deployment_base_python=base_python,
        deployment_base_slurm_profile=base_profile,
    )
    binding = {
        'schema': RUNTIME_BINDING_SCHEMA,
        'environment_id': normalized_environment,
        'release_id': selected_release_id,
        'local_source_root': str(root),
        'remote_profile': normalized_target,
        'remote_server_profile': selected_server_profile,
        'deployment_base_python': base_python,
        'deployment_base_slurm_profile': base_profile,
        'remote_release_root': remote_result.get('release_root'),
        'runtime_identity_file': str(identity_path),
        'remote_config': str(local_config),
    }
    binding_path = identity_path.parent / 'runtime-binding.json'
    binding_path.write_text(
        json.dumps(binding, ensure_ascii=False, indent=2) + '\n',
        encoding='utf-8',
    )
    binding_path.chmod(0o600)

    verification = None
    if verify:
        capabilities = SshSlurmExecutor.from_config(
            normalized_target,
            str(local_config),
        ).remote_capabilities()
        verification = {
            'cluster_id': capabilities.get('cluster_id'),
            'runtime_identity': capabilities.get('runtime_identity'),
            'matched': True,
        }
    return {
        'schema': 'pyscf-agent.worktree-deployment.v1',
        'binding': binding,
        'remote_release': remote_result,
        'runtime_identity': identity.to_dict(),
        'verification': verification,
    }


__all__ = ['RUNTIME_BINDING_SCHEMA', 'deploy_worktree_remote']
