#!/usr/bin/env python3
"""Bind the plugin to an installed agent and fixed paths; no scientific execution."""

from __future__ import annotations

import os
from pathlib import Path
import shlex
import sys


def default_config_path() -> Path:
    override = os.environ.get('PYSCF_AGENT_CODEX_CONFIG')
    if override:
        return Path(override).expanduser().absolute()
    root = Path(os.environ.get('XDG_CONFIG_HOME') or Path.home() / '.config')
    return root.expanduser().absolute() / 'pyscf-agent' / 'codex-mcp.sh'


def server_arguments(args) -> list[str]:
    from pyscf_agent.executors.remote_config import resolve_remote_config_path
    from pyscf_agent.executors.slurm_config import resolve_slurm_config_path

    arguments = ['--work-dir', str(Path(args.work_dir).expanduser().absolute()),
                 '--executor', args.executor]
    if args.executor == 'remote':
        arguments += ['--remote-config', str(resolve_remote_config_path(args.remote_config)),
                      '--remote', args.remote]
    elif args.executor == 'slurm':
        arguments += ['--slurm-config', str(resolve_slurm_config_path(args.slurm_config))]
        if args.slurm_profile:
            arguments += ['--slurm-profile', args.slurm_profile]
    if args.local_wall_time_seconds is not None:
        arguments += ['--local-wall-time-seconds', str(args.local_wall_time_seconds)]
    return arguments


def write_configuration(path: Path, arguments: list[str], *, force=False, python=None) -> None:
    # Do not resolve a venv's Python symlink to the base interpreter.
    executable = os.path.abspath(python or sys.executable)
    command = shlex.join([executable, '-m', 'pyscf_agent.mcp_server', *arguments])
    content = ('#!/bin/sh\n# Generated by the PySCF Agent Codex plugin.\n'
               '# Runtime paths belong to this machine, not the plugin cache.\n'
               'set -eu\nexec ' + command + ' "$@"\n')
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w' if force else 'x', encoding='utf-8') as stream:
        stream.write(content)
    path.chmod(0o600)


def main(argv=None) -> int:
    if sys.version_info < (3, 10):
        print('PySCF Agent requires Python 3.10 or newer.', file=sys.stderr)
        return 2
    try:
        from pyscf_agent.mcp_server.cli import build_parser
        from pyscf_agent.executors.factory import create_task_executor_from_args
    except ModuleNotFoundError as exc:
        print(f'Install pyscf-agent[mcp] in this Python environment first: {exc}', file=sys.stderr)
        return 2

    parser = build_parser()
    parser.description = 'Configure the local Codex plugin using this installed agent environment.'
    from pyscf_agent.paths import default_runs_root
    parser.set_defaults(work_dir=str(default_runs_root()))
    parser.add_argument('--config-file', type=Path, default=default_config_path(),
                        help='Local launcher configuration; normally outside the plugin directory.')
    parser.add_argument('--force', action='store_true', help='Replace an existing local configuration.')
    args = parser.parse_args(argv)
    try:
        # Check the actual SDK entry point, not just the presence of an mcp module.
        from pyscf_agent.mcp_server.server import create_server  # noqa: F401
        create_task_executor_from_args(args)  # Configuration validation only; no SSH or jobs.
        destination = args.config_file.expanduser().absolute()
        write_configuration(destination, server_arguments(args), force=args.force)
    except FileExistsError:
        parser.error('Configuration already exists; use --force to replace it.')
    except (ImportError, OSError, TypeError, ValueError) as exc:
        parser.error(str(exc))
    print(f'Configured {destination}')
    print(f'Python: {sys.executable}')
    print(f'Execution target: {args.executor}')
    print(f'Calculation directory: {Path(args.work_dir).expanduser().absolute()}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
