from __future__ import annotations

from pyscf_agent.schema_contracts import BATCH_HANDLE_SCHEMA, JOB_STATUS_SCHEMA, SLURM_BATCH_MANIFEST_SCHEMA, STUDY_EXECUTION_RECEIPT_SCHEMA, STUDY_PLAN_SCHEMA, STUDY_REPORT_SCHEMA, TASK_REPORT_SCHEMA

from typing import List

from ...schema_contracts import ADAPTIVE_STUDY_REPORT_SCHEMA
from ..contracts import ArtifactContract


def build_default_artifact_contracts() -> List[ArtifactContract]:
    return [
        ArtifactContract(
            id='artifact_reference',
            label='Artifact reference metadata',
            required_reference_fields=(
                'kind',
                'path',
                'size_bytes',
                'mime_type',
                'description',
            ),
        ),
        ArtifactContract(
            id='single_task_core',
            label='Single-task core artifacts',
            artifact_kinds=(
                'generated_input',
                'structured_results',
                'raw_scf_output',
                'raw_stdout',
                'numerical_array',
                'task_detail',
            ),
            binary_artifact_kinds=('numerical_array',),
            payload_schemas={
                'structured_results': 'pyscf-agent.structured-results.v1',
            },
        ),
        ArtifactContract(
            id='molecular_dynamics',
            label='Molecular-dynamics trajectory artifacts',
            description=(
                'Compact trajectory manifest plus sampled coordinates, '
                'velocities, energies, Fock matrices, and overlap matrices.'
            ),
            artifact_kinds=(
                'molecular_md_manifest',
                'molecular_md_frame_arrays',
                'molecular_md_failure',
            ),
            payload_schemas={
                'molecular_md_manifest': 'pyscf-agent.molecular-md-manifest.v1',
                'molecular_md_frame_arrays': 'pyscf-agent.molecular-md-frame-arrays.v1',
                'molecular_md_failure': 'pyscf-agent.molecular-md-failure.v1',
            },
            binary_artifact_kinds=('molecular_md_frame_arrays',),
            result_fields=('trajectory',),
            numeric_container='NPZ',
        ),
        ArtifactContract(
            id='hamiltonian_dataset_collection',
            label='Generated and collected Hamiltonian dataset artifacts',
            description=(
                'A lightweight generation receipt plus optional local copies of '
                'a portable dataset and its trajectory NPZ files.'
            ),
            artifact_kinds=(
                'hamiltonian_dataset_generation_receipt',
                'hamiltonian_collected_dataset_manifest',
                'hamiltonian_collected_sample_index',
                'hamiltonian_collected_rejection_index',
                'hamiltonian_collected_trajectory_arrays',
            ),
            payload_schemas={
                'hamiltonian_dataset_generation_receipt': (
                    'pyscf-agent.hamiltonian-dataset-generation.v1'
                ),
                'hamiltonian_collected_dataset_manifest': (
                    'pyscf-agent.hamiltonian-dataset-manifest.v1'
                ),
            },
            binary_artifact_kinds=('hamiltonian_collected_trajectory_arrays',),
            numeric_container='NPZ',
        ),
        ArtifactContract(
            id='compiled_workflow',
            label='Compiled workflow configuration and provenance',
            artifact_kinds=(
                'workflow-configuration',
                'workflow-provenance',
                'workflow-execution-trace',
                'gate-configuration',
                'gate-provenance',
                'gate-execution-trace',
            ),
            payload_schemas={
                'workflow-configuration': 'pyscf-agent.workflow-configuration.v1',
                'workflow-provenance': 'pyscf-agent.workflow-provenance.v1',
                'workflow-execution-trace': 'pyscf-agent.workflow-execution-trace.v1',
                'gate-configuration': 'pyscf-agent.gate-configuration.v1',
                'gate-provenance': 'pyscf-agent.gate-provenance.v1',
                'gate-execution-trace': 'pyscf-agent.gate-execution-trace.v1',
            },
        ),
        ArtifactContract(
            id='execution_job',
            label='Submitted task lifecycle artifacts',
            artifact_kinds=('job-state', 'task-report', 'execution-receipt', 'study-invocation'),
            payload_schemas={
                'job-state': JOB_STATUS_SCHEMA,
                'task-report': TASK_REPORT_SCHEMA,
                'execution-receipt': STUDY_EXECUTION_RECEIPT_SCHEMA,
                'study-invocation': 'pyscf-agent.study-invocation.v1',
            },
        ),
        ArtifactContract(
            id='slurm_batch_execution',
            label='Slurm batch execution artifacts',
            artifact_kinds=('slurm-batch-manifest', 'slurm-batch-handle'),
            payload_schemas={
                'slurm-batch-manifest': SLURM_BATCH_MANIFEST_SCHEMA,
                'slurm-batch-handle': BATCH_HANDLE_SCHEMA,
            },
        ),
        ArtifactContract(
            id='molecular_correlation',
            label='Molecular correlation artifacts',
            artifact_kinds=(
                'correlation_diagnostics',
                'scf_stability',
                'orbital_processing',
                'orbital_summary_table',
                'active_space',
                'active_space_summary_table',
                'active_space_audit',
                'active_space_audit_table',
                'cas_result',
                'sc_nevpt2',
                'one_particle_state',
                'one_particle_state_metadata',
                'ccsd_label_arrays',
                'ccsd_label_manifest',
            ),
            payload_schemas={
                'correlation_diagnostics': 'pyscf-agent.molecular-correlation-diagnostics.v1',
                'scf_stability': 'pyscf-agent.scf-stability.v1',
                'orbital_processing': 'pyscf-agent.orbital-processing.v1',
                'active_space': 'pyscf-agent.active-space.v1',
                'active_space_audit': 'pyscf-agent.active-space-audit.v1',
                'cas_result': 'pyscf-agent.cas-result.v1',
                'sc_nevpt2': 'pyscf-agent.sc-nevpt2.v1',
                'one_particle_state_metadata': 'pyscf-agent.one-particle-state.v1',
                'ccsd_label_arrays': 'pyscf-agent.ccsd-labels.v2',
                'ccsd_label_manifest': 'pyscf-agent.ccsd-labels.v2',
            },
        ),
        ArtifactContract(
            id='block2_dmrg',
            label='block2 DMRG solver artifacts',
            artifact_kinds=(
                'block2_dmrg_result',
                'block2_bond_dimension_plan',
                'block2_dmrg_casscf',
                'block2_dmrg_arrays',
                'block2_mps_manifest',
                'entanglement_active_space_recommendation',
            ),
            payload_schemas={
                'block2_dmrg_result': 'pyscf-agent.block2-dmrg-result.v1',
                'block2_bond_dimension_plan': 'pyscf-agent.block2-bond-dimension-plan.v1',
                'block2_dmrg_casscf': 'pyscf-agent.block2-dmrg-casscf.v1',
                'block2_mps_manifest': 'pyscf-agent.block2-mps-manifest.v1',
                'entanglement_active_space_recommendation': 'pyscf-agent.entanglement-active-space-recommendation.v1',
            },
            binary_artifact_kinds=('block2_dmrg_arrays',),
            result_fields=(
                'energy',
                'state_energies',
                'excitation_energies',
                'state_average_energy',
                'state_average_weights',
                'natural_occupations',
                'entanglement_diagnostics',
                'entanglement_active_space_recommendation',
                'symmetry_analysis',
                'adaptive_schedule',
                'bond_dimension_plan',
                'energy_error_estimate',
                'orbital_ordering',
                'orbital_provenance',
                'restart',
                'checkpoint_manifest',
                'casscf',
                'result_contract_schema',
                'requested_root_count',
                'computed_root_count',
                'targeted_roots_complete',
                'state_sector',
                'root_signatures',
                'final_bond_dimension',
                'maximum_bond_dimension',
                'final_discarded_weight',
                'final_energy_change',
                'sweeps_completed',
                'estimated_absolute_energy_error',
                'checkpoint_available',
                'result_scope',
                'recovery_recommendation',
            ),
            continuation_contract=(
                'A compatible block2_mps_manifest may initialize a later fixed-orbital task. '
                'Cross-task DMRG-CASSCF continuation restores a joint optimized-orbital/MPS '
                'checkpoint. Active-space expansion restores optimized orbitals only and starts '
                'a fresh MPS.'
            ),
        ),
        ArtifactContract(
            id='model_hamiltonian',
            label='Model-Hamiltonian artifacts',
            artifact_kinds=(
                'model_hamiltonian_spec',
                'model_hamiltonian_energy_levels',
                'model_hamiltonian_energy_levels_txt',
                'strong_correlation_diagnostics',
            ),
            artifact_kind_patterns=('observable-*',),
            payload_schemas={
                'model_hamiltonian_spec': 'pyscf-agent.model-hamiltonian.v1',
                'model_hamiltonian_energy_levels': 'pyscf-agent.model-energy-levels.v1',
                'strong_correlation_diagnostics': 'pyscf-agent.strong-correlation-diagnostics.v1',
            },
        ),
        ArtifactContract(
            id='model_bloch',
            label='Bloch model artifacts',
            artifact_kinds=(
                'model_bloch_bands',
                'model_bloch_bands_tsv',
                'model_bloch_dos',
                'model_bloch_dos_tsv',
                'model_bloch_kmesh',
                'model_bloch_kmesh_tsv',
                'model_bloch_hamiltonian_samples',
            ),
            payload_schemas={
                'model_bloch_bands': 'pyscf-agent.model-bloch-bands.v1',
                'model_bloch_dos': 'pyscf-agent.model-bloch-dos.v1',
                'model_bloch_kmesh': 'pyscf-agent.model-bloch-kmesh.v1',
            },
        ),
        ArtifactContract(
            id='periodic',
            label='Periodic electronic-structure artifacts',
            artifact_kinds=(
                'periodic_task_input',
                'periodic_structure_source',
                'periodic_cell',
                'periodic_structure_normalized',
                'periodic_input_cell',
                'periodic_input_structure_normalized',
                'periodic_seekpath_standardization',
                'periodic_numerics',
                'periodic_orbitals',
                'periodic_band_structure',
                'periodic_band_structure_tsv',
                'periodic_scf_summary',
            ),
            payload_schemas={
                'periodic_task_input': 'pyscf-agent.periodic-task.v1',
                'periodic_cell': 'pyscf-agent.periodic-structure.v1',
                'periodic_input_cell': 'pyscf-agent.periodic-structure.v1',
                'periodic_seekpath_standardization': 'pyscf-agent.periodic-seekpath-standardization.v1',
                'periodic_numerics': 'pyscf-agent.periodic-numerics.v1',
                'periodic_orbitals': 'pyscf-agent.periodic-orbitals.v1',
                'periodic_band_structure': 'pyscf-agent.periodic-band-structure.v1',
                'periodic_scf_summary': 'pyscf-agent.periodic-scf-summary.v1',
            },
        ),
        ArtifactContract(
            id='computational_study',
            label='Computational-study artifacts',
            artifact_kinds=(
                'study-plan',
                'cost-estimate',
                'study-state',
                'retry-action',
                'dmet-continuation-action',
                'dmet-phase-analysis',
                'grid-refinement-state',
                'study-group',
                'comparison-table',
                'study-report',
            ),
            artifact_kind_patterns=('observable-*',),
            payload_schemas={
                'study-plan': STUDY_PLAN_SCHEMA,
                'cost-estimate': 'pyscf-agent.cost-estimate.v1',
                'study-state': 'pyscf-agent.study-state.v1',
                'dmet-continuation-action': 'pyscf-agent.dmet-continuation-action.v1',
                'dmet-phase-analysis': 'pyscf-agent.dmet-branch-analysis.v1',
                'grid-refinement-state': 'pyscf-agent.grid-refinement-state.v1',
                'study-group': 'pyscf-agent.grid-group.v1',
                'study-report': STUDY_REPORT_SCHEMA,
            },
        ),
        ArtifactContract(
            id='hamiltonian_dataset',
            label='Hamiltonian dataset artifacts',
            description='Accepted/rejected sample indexes and the finalized dataset manifest.',
            artifact_kinds=(
                'hamiltonian_dataset_manifest',
                'hamiltonian_sample_index',
                'hamiltonian_rejection_index',
            ),
            payload_schemas={
                'hamiltonian_dataset_manifest': 'pyscf-agent.hamiltonian-dataset-manifest.v1',
                'hamiltonian_sample_index': 'pyscf-agent.hamiltonian-sample.v1',
                'hamiltonian_rejection_index': 'pyscf-agent.hamiltonian-sample-rejection.v1',
            },
        ),
        ArtifactContract(
            id='adaptive_study',
            label='Adaptive-study artifacts',
            artifact_kinds=(
                'adaptive-request-manifest',
                'adaptive-initial-scan-plan',
                'adaptive-initial-scan-report',
                'adaptive-refined-plan',
                'adaptive-decision-log',
                'scan-path-diagnostics',
                'adaptive-path-window-restart-plan',
                'adaptive-path-window-restart-validation',
                'adaptive-mps-continuation-plan',
                'adaptive-dmrg-state-tracking',
                'adaptive-path-refinement-plan',
                'adaptive-study-report',
            ),
            payload_schemas={
                'adaptive-request-manifest': 'pyscf-agent.adaptive-request.v1',
                'adaptive-initial-scan-plan': STUDY_PLAN_SCHEMA,
                'adaptive-initial-scan-report': STUDY_REPORT_SCHEMA,
                'adaptive-refined-plan': STUDY_PLAN_SCHEMA,
                'adaptive-decision-log': 'pyscf-agent.adaptive-decision-log.v1',
                'scan-path-diagnostics': 'pyscf-agent.scan-path-diagnostics.v1',
                'adaptive-path-window-restart-plan': 'pyscf-agent.path-window-restart.v1',
                'adaptive-path-window-restart-validation': 'pyscf-agent.path-window-restart-validation.v1',
                'adaptive-mps-continuation-plan': 'pyscf-agent.mps-continuation-review.v1',
                'adaptive-dmrg-state-tracking': 'pyscf-agent.dmrg-state-tracking.v1',
                'adaptive-path-refinement-plan': STUDY_PLAN_SCHEMA,
                'adaptive-study-report': ADAPTIVE_STUDY_REPORT_SCHEMA,
            },
        ),
        ArtifactContract(
            id='embedding_interchange',
            label='Embedding interchange artifacts',
            artifact_kinds=(
                'embedding_reference',
                'localized_subspace',
                'localized_hamiltonian',
                'correlated_subspace_audit',
            ),
            binary_artifact_kinds=(
                'embedding_reference',
                'localized_subspace',
                'localized_hamiltonian',
            ),
            payload_schemas={
                'embedding_reference': 'pyscf-agent.embedding-reference.v1',
                'localized_subspace': 'pyscf-agent.localized-subspace.v1',
                'localized_hamiltonian': 'pyscf-agent.localized-hamiltonian.v1',
                'correlated_subspace_audit': 'pyscf-agent.correlated-subspace-audit.v1',
            },
            result_fields=('embedding_preparation',),
            numeric_container='HDF5',
        ),
        ArtifactContract(
            id='dmet',
            label='DMET execution artifacts',
            artifact_kinds=(
                'dmet_result',
                'dmet_iteration_history',
                'dmet_numerical_arrays',
                'dmet_mean_field_state',
                'dmet_output_log',
            ),
            binary_artifact_kinds=('dmet_numerical_arrays', 'dmet_mean_field_state'),
            payload_schemas={
                'dmet_result': 'pyscf-agent.dmet-result.v1',
                'dmet_iteration_history': 'pyscf-agent.dmet-iteration-history.v1',
                'dmet_numerical_arrays': 'pyscf-agent.dmet-numerical-arrays.v1',
                'dmet_mean_field_state': 'pyscf-agent.dmet-mean-field-state.v1',
            },
            numeric_container='NPZ',
        ),
        ArtifactContract(
            id='hf_dmft',
            label='fcDMFT HF+DMFT execution artifacts',
            artifact_kinds=(
                'hf_dmft_result',
                'hf_dmft_arrays',
                'hf_dmft_output_log',
                'hf_dmft_checkpoint',
            ),
            binary_artifact_kinds=('hf_dmft_arrays', 'hf_dmft_checkpoint'),
            payload_schemas={
                'hf_dmft_result': 'pyscf-agent.hf-dmft-result.v1',
                'hf_dmft_arrays': 'pyscf-agent.hf-dmft-arrays.v1',
            },
            result_fields=(
                'dmft_result',
                'reference_energy',
                'mean_field_energy',
                'final_method',
                'energy_kind',
            ),
            numeric_container='NPZ and HDF5',
        ),
        ArtifactContract(
            id='periodic_gw',
            label='fcDMFT periodic GW artifacts',
            artifact_kinds=(
                'periodic_gw_result',
                'periodic_gw_arrays',
                'periodic_gw_output_log',
                'periodic_gw_analytic_continuation',
                'periodic_gw_mean_field_potential',
                'periodic_gw_imaginary_self_energy',
            ),
            binary_artifact_kinds=(
                'periodic_gw_arrays',
                'periodic_gw_analytic_continuation',
                'periodic_gw_mean_field_potential',
                'periodic_gw_imaginary_self_energy',
            ),
            payload_schemas={
                'periodic_gw_result': 'pyscf-agent.periodic-gw-result.v1',
                'periodic_gw_arrays': 'pyscf-agent.periodic-gw-arrays.v1',
            },
            result_fields=('gw_result', 'gap', 'final_method', 'energy_kind'),
            numeric_container='NPZ and HDF5',
        ),
        ArtifactContract(
            id='gw_dmft',
            label='fcDMFT GW+DMFT execution artifacts',
            artifact_kinds=(
                'gw_dmft_local_analytic_continuation',
                'gw_dmft_local_imaginary_self_energy',
                'gw_dmft_local_orbital_transform',
                'gw_dmft_local_output_log',
                'gw_dmft_result',
                'gw_dmft_arrays',
                'gw_dmft_output_log',
                'gw_dmft_checkpoint',
            ),
            binary_artifact_kinds=(
                'gw_dmft_local_analytic_continuation',
                'gw_dmft_local_imaginary_self_energy',
                'gw_dmft_local_orbital_transform',
                'gw_dmft_arrays',
                'gw_dmft_checkpoint',
            ),
            payload_schemas={
                'gw_dmft_result': 'pyscf-agent.gw-dmft-result.v1',
                'gw_dmft_arrays': 'pyscf-agent.gw-dmft-arrays.v1',
            },
            result_fields=(
                'gw_result',
                'gw_double_counting_result',
                'dmft_result',
                'reference_energy',
                'final_method',
                'energy_kind',
            ),
            numeric_container='NPZ and HDF5',
        ),
        ArtifactContract(
            id='postprocessing',
            label='Postprocessing artifacts',
            artifact_kinds=(
                'postprocess-plot',
                'postprocess-plot-spec',
                'postprocess-plot-data-tsv',
                'postprocess-plot-data-json',
            ),
            payload_schemas={
                'postprocess-plot-spec': 'pyscf-agent.postprocess-plot-spec.v1',
                'postprocess-plot-data-json': 'pyscf-agent.postprocess-plot-data.v1',
            },
        ),
        ArtifactContract(
            id='trajectory_frame_selection',
            label='Energy-stratified trajectory frame selection',
            artifact_kinds=('trajectory_frame_selection', 'selected_trajectory_frames',
                            'selected_trajectory_xyz'),
            payload_schemas={
                'trajectory_frame_selection': 'pyscf-agent.trajectory-frame-selection.v1',
                'selected_trajectory_frames': 'pyscf-agent.selected-trajectory-frame.v1',
            },
        ),
    ]


__all__ = ['build_default_artifact_contracts']
