from __future__ import annotations

from typing import Any, Callable, Dict, List


def build_model_hamiltonian_families(
    item_factory: Callable[..., Any],
    *,
    capability_design_only: str,
    capability_planned: str,
) -> Dict[str, List[Any]]:
    _capability = item_factory
    CAPABILITY_DESIGN_ONLY = capability_design_only
    CAPABILITY_PLANNED = capability_planned

    return {
        'model_hamiltonian_models': [
            _capability('hubbard', 'Hubbard model', 'model_hamiltonian.model'),
            _capability(
                'holstein_hubbard',
                'Holstein-Hubbard model',
                'model_hamiltonian.model',
                CAPABILITY_DESIGN_ONLY,
                planner_allowed=False,
                backend_allowed=False,
                ui_visibility='hidden',
                limitations=['Builder can describe phonon fields, but backend solvers do not support phonon Hilbert spaces yet.'],
            ),
        ],
        'model_hamiltonian_solvers': [
            _capability('mp2', 'MP2', 'model_hamiltonian.solver'),
            _capability('ccsd', 'CCSD', 'model_hamiltonian.solver'),
            _capability(
                'ccsd_t',
                'CCSD(T)',
                'model_hamiltonian.solver',
                metadata={
                    'aliases': ['ccsd(t)', 'ccsd-t', 'ccsdt', 'ccsd triples'],
                    'result_field': 'triples_correction',
                    'result_shape': 'scalar',
                    'unit': 'a.u.',
                    'generated_output_rule': 'Model Hamiltonian CCSD(T) produces a perturbative triples correction when the triples_correction field is present.',
                },
            ),
            _capability(
                'fci',
                'Full CI / exact diagonalization',
                'model_hamiltonian.solver',
                metadata={
                    'aliases': [
                        'full ci',
                        'full-ci',
                        'fullci',
                        'exact',
                        'exact diagonalization',
                        'exact-diagonalization',
                        'ed',
                    ],
                    'diagnostic_spectrum': 'full_diagonalization',
                    'full_diagonalization_max_dimension': 5000,
                    'solver_options': {
                        'nroots': {
                            'type': 'integer',
                            'minimum': 1,
                            'default': 1,
                            'meaning': 'Number of lowest many-body eigenstates in the selected particle/spin sector.',
                        },
                    },
                },
                limitations=[
                    'Strong-correlation spectrum diagnostics use full dense diagonalization and are limited to determinant dimension 5,000.',
                ],
            ),
            _capability(
                'block2_dmrg',
                'block2 DMRG',
                'model_hamiltonian.solver',
                required_provider_ids=('provider.block2',),
                metadata={
                    'aliases': ['block2', 'block2-dmrg', 'dmrg'],
                    'requires_representation': 'finite_cluster',
                    'optional_dependency': 'block2',
                    'supports_spin_resolved_rdms': True,
                    'solver_options': {
                        'mpo_algorithm': {
                            'enum': ['fast_bipartite', 'conventional'],
                            'default': 'conventional',
                            'meaning': 'MPO construction for the electronic Hamiltonian; Conventional uses NC for two sites.',
                        },
                        'nroots': {
                            'type': 'integer',
                            'minimum': 1,
                            'default': 1,
                            'meaning': 'Number of targeted low-lying states in the selected particle/spin sector.',
                        },
                    },
                    'artifact_kinds': [
                        'block2_dmrg_result',
                        'block2_bond_dimension_plan',
                        'block2_dmrg_arrays',
                        'block2_mps_manifest',
                    ],
                    'adaptive_convergence': True,
                    'adaptive_convergence_controls': [
                        'max_adaptive_stages',
                        'max_bond_dimension',
                        'bond_dimension_growth_factor',
                        'adaptive_sweeps',
                        'adaptive_noise',
                    ],
                    'bond_dimension_planning': {
                        'method': 'fixed_particle_number_schmidt_rank',
                        'result_field': 'bond_dimension_plan',
                    },
                    'energy_error_estimate': 'discarded_weight_extrapolation_or_final_sweep_change',
                    'result_contract_schema': 'pyscf-agent.block2-result-contract.v1',
                    'recovery_schema': 'pyscf-agent.block2-recovery-recommendation.v1',
                },
                limitations=[
                    'Targeted low-lying roots are available on request, but they are not a complete spectrum; cross-case identity is reviewed during explicit result analysis.',
                    'Convergence is accepted only when both energy change and discarded weight meet their configured tolerances.',
                ],
            ),
            _capability(
                'dmet',
                'libDMET DMET',
                'model_hamiltonian.solver',
                required_provider_ids=('provider.libdmet',),
                metadata={
                    'aliases': ['libdmet', 'density matrix embedding theory'],
                    'requires_representation': 'finite_cluster',
                    'solver_options': {
                        'impurity_solver': {
                            'type': 'string',
                            'enum': ['fci', 'ccsd', 'block2_dmrg'],
                            'default': 'fci',
                        },
                        'impurity_solver_options': {
                            'type': 'object',
                            'default': {},
                            'meaning': 'Provider-specific options: shared SCF/fitting beta for CCSD or opt-in FCI, or block2 schedules, ordering, threading, and memory.',
                        },
                        'impurity_shape': {
                            'type': 'array',
                            'items': {'type': 'integer', 'minimum': 1},
                            'default': [],
                            'meaning': 'Fragment shape in Builder primitive-cell units; all basis sites in each selected cell are retained.',
                        },
                        'impurity_size': {
                            'type': 'integer',
                            'minimum': 1,
                            'default': None,
                            'meaning': 'Sites per fragment for graphs without multi-site primitive-cell metadata.',
                        },
                        'impurity_site_ids': {
                            'type': 'array',
                            'items': {'type': 'integer', 'minimum': 0},
                            'default': [],
                            'meaning': 'Convenience selector for one explicit impurity.',
                        },
                        'fragments': {
                            'type': 'array',
                            'items': {
                                'type': 'object',
                                'required': ['site_ids'],
                                'properties': {
                                    'fragment_id': {'type': 'string'},
                                    'site_ids': {
                                        'type': 'array',
                                        'items': {'type': 'integer', 'minimum': 0},
                                    },
                                },
                            },
                            'default': [],
                            'meaning': 'Canonical explicit fragment partition using Builder site ids.',
                        },
                        'reference': {
                            'type': 'string',
                            'enum': ['restricted', 'unrestricted'],
                            'default': 'unrestricted',
                            'meaning': 'Unrestricted is the Hubbard default and uses the fixed Nalpha-Nbeta sector from ModelSpec.nelec.',
                        },
                        'execution_mode': {
                            'type': 'string',
                            'enum': ['translational', 'finite_graph'],
                            'resolution_policy': 'translational_if_eligible_else_finite_graph',
                            'meaning': 'Use one translated representative impurity or preserve the complete Builder graph as an explicit fragment partition.',
                        },
                        'fragment_definition': {
                            'type': 'string',
                            'enum': ['primitive_cell', 'cell_shape', 'site_count', 'honeycomb_hexagon'],
                            'resolution_policy': 'explicit_selector_else_primitive_cell',
                            'meaning': 'Use a primitive cell, a cell block, a site-count partition, or disjoint honeycomb six-site rings. honeycomb_hexagon uses finite-graph DMET and requires a compatible periodic lattice (e.g. 3x3 or 6x6 primitive cells, not 4x4). Do not combine it with other fragment selectors.',
                        },
                        'interacting_bath': {
                            'type': 'boolean',
                            'default': True,
                            'meaning': 'Project lattice two-body interactions into the full embedding basis; false keeps interactions on the impurity only.',
                        },
                        'initial_correlation_potential': {
                            'type': 'string',
                            'enum': ['zero'],
                            'default': 'zero',
                            'meaning': 'Start DMET from an unbiased zero auxiliary correlation potential.',
                        },
                        'reference_density_guess': {
                            'type': 'string',
                            'enum': ['pm', 'af', 'fm', 'cdw'],
                            'default': 'pm',
                            'meaning': 'Select only the initial reference-density seed (spin or sublattice-charge bias); vcor remains zero.',
                        },
                        'reference_density_source': {
                            'type': 'object', 'default': None,
                            'properties': {
                                'source_case_id': {'type': 'string'},
                                'source_run_id': {'type': 'string'},
                                'path': {'type': 'string'},
                                'sha256': {'type': 'string'},
                            },
                            'additionalProperties': False,
                            'meaning': 'Finite-graph warm start from a converged DMET mean-field density. Specify a Study source_case_id or an absolute artifact path with sha256. Overrides the analytic density seed; target U/V rebuild the physical baseline and the auxiliary correction starts at zero.',
                        },
                        'reference_density_bias': {
                            'type': 'number',
                            'minimum': 0,
                            'default': 0.05,
                            'meaning': 'Staggered seed amplitude used by AF (spin density) and CDW (charge density, per spin) initialization.',
                        },
                        'max_iterations': {'type': 'integer', 'minimum': 1, 'default': 50},
                        'correlation_potential_mixing': {
                            'type': 'number',
                            'exclusiveMinimum': 0,
                            'maximum': 1,
                            'default': 1.0,
                            'meaning': 'Fraction of the proposed outer DMET correlation-potential update retained after optional DIIS; 1 disables damping.',
                        },
                        'diis_enabled': {
                            'type': 'boolean',
                            'default': True,
                            'meaning': 'Enable outer DMET DIIS extrapolation; independent of impurity SCF DIIS.',
                        },
                        'diis_start': {'type': 'integer', 'minimum': 1, 'default': 4},
                        'diis_space': {'type': 'integer', 'minimum': 1, 'default': 4},
                        'trace_fix_start': {'type': 'integer', 'minimum': 1, 'default': 3},
                        'energy_tolerance': {
                            'type': 'number',
                            'exclusiveMinimum': 0,
                            'default': 1e-6,
                            'meaning': 'Native libDMET threshold for the DMET energy change.',
                        },
                        'density_tolerance': {
                            'type': 'number',
                            'exclusiveMinimum': 0,
                            'default': 1e-4,
                            'meaning': 'Native libDMET threshold for the maximum consecutive mean-field 1RDM change.',
                        },
                        'density_fit_tolerance': {
                            'type': 'number',
                            'exclusiveMinimum': 0,
                            'default': 1e-4,
                            'meaning': 'Diagnostic limit for the mismatch between the correlated embedding density and the auxiliary mean-field density; reported in quality checks, not a convergence criterion.',
                        },
                        'solver_tolerance': {
                            'type': 'number',
                            'exclusiveMinimum': 0,
                            'default': 1e-10,
                        },
                        'solver_max_cycle': {'type': 'integer', 'minimum': 1, 'default': 200},
                        'bath_spin_dimension_policy': {
                            'type': 'string', 'enum': ['native', 'max'], 'default': 'native',
                            'meaning': 'For finite-graph noninteracting eigenvalue baths, complete the smaller spin bath to the larger dimension with omitted orthonormal environment eigenvectors.',
                        },
                        'impurity_scf_diis': {
                            'type': 'boolean',
                            'default': True,
                            'meaning': 'Use DIIS in preliminary impurity SCF: native DIIS for FCI, ADIIS/CDIIS blending for CCSD. CCSD requires converged SCF before proceeding. The block2 bridge has no preliminary SCF.',
                        },
                        'solver_max_memory_mb': {'type': 'integer', 'minimum': 1, 'default': 40000},
                    },
                    'artifact_kinds': [
                        'dmet_result',
                        'dmet_iteration_history',
                        'dmet_numerical_arrays',
                        'dmet_mean_field_state',
                    ],
                    'conditional_providers': {
                        'impurity_solver=block2_dmrg': ['provider.block2'],
                    },
                },
                limitations=[
                    'Restricted and fixed-spin unrestricted references are supported; libDMET Sz is Nalpha-Nbeta.',
                    'Nonzero-spin execution currently requires one translated representative fragment.',
                    'Ground-state DMET only; excited-state requests are not supported.',
                    'Interacting Schmidt baths are the default; the noninteracting-bath approximation must be requested explicitly.',
                    'The initial auxiliary correlation potential is fixed to zero; PM, AF, and FM affect only the self-consistent reference density.',
                    'Self-consistency requires representative-fragment energy, mean-field 1RDM, and density-fit residual convergence; correlation-potential changes remain diagnostic only.',
                    'Uniform chain/ring and square presets use the native translated lattice path. Periodic Builder graphs with complete primitive-cell metadata may use a translation-audited representative impurity, including multi-site cells.',
                    'Open, nonuniform, locally edited, extended-Hubbard, or translation-inequivalent Builder graphs preserve the original Hamiltonian through an explicit finite-graph fragment partition.',
                    'Builder primitive-cell metadata defines the default fragment for multi-site cells; impurity_shape and impurity_size are alternative selectors, not simultaneous inputs.',
                    'block2 DMRG uses a ground-state impurity solve with mandatory 1- and 2-RDMs and internal MPS continuation between DMET iterations.',
                ],
            ),
            _capability(
                'tight_binding',
                'Bloch tight binding',
                'model_hamiltonian.solver',
                planner_allowed=False,
                ui_visibility='hidden',
                metadata={
                    'aliases': ['tb', 'tight-binding', 'tight binding'],
                    'requires_representation': 'bloch',
                    'interaction_treatment': 'one_body_only',
                    'resource_limits': {
                        'max_kpoints': 50000,
                        'max_path_vertices': 64,
                        'max_path_points': 20000,
                        'max_dos_points': 4001,
                        'max_dos_work_items': 200000000,
                    },
                    'generated_outputs': [
                        'band_gap',
                        'direct_gap',
                        'fermi_energy',
                        'bandwidth',
                        'bloch_band_structure',
                        'bloch_dos',
                        'bloch_kmesh',
                    ],
                },
                limitations=[
                    'Diagonalizes the one-body Bloch Hamiltonian h(k).',
                    'U and V are retained in the input but are not applied by this solver.',
                    'Adaptive planner routing for Bloch studies is not enabled yet.',
                    'Reciprocal-space mesh, path, and DOS requests are bounded before allocation.',
                ],
            ),
        ],
        'model_hamiltonian_builder_templates': [
            _capability('chain', '1D chain', 'model_hamiltonian.builder_template'),
            _capability('ring', '1D ring', 'model_hamiltonian.builder_template'),
            _capability('zigzag', '1D zigzag', 'model_hamiltonian.builder_template'),
            _capability('quasi_1d', 'Quasi-1D ladder', 'model_hamiltonian.builder_template'),
            _capability('square', 'Square lattice', 'model_hamiltonian.builder_template'),
            _capability('lieb', 'Lieb lattice', 'model_hamiltonian.builder_template'),
            _capability('honeycomb', 'Honeycomb lattice', 'model_hamiltonian.builder_template'),
            _capability('triangular', 'Triangular lattice', 'model_hamiltonian.builder_template'),
            _capability('kagome', 'Kagome lattice', 'model_hamiltonian.builder_template'),
            _capability('dice', 'Dice lattice', 'model_hamiltonian.builder_template'),
            _capability('square_octagon', 'Square-octagon lattice', 'model_hamiltonian.builder_template'),
        ],
        'model_hamiltonian_parameters': [
            _capability('t', 'Hopping t', 'model_hamiltonian.parameter', metadata={'scopes': ['bond', 'global', 'sweep']}),
            _capability('U', 'On-site U', 'model_hamiltonian.parameter', metadata={'scopes': ['site', 'global', 'sweep']}),
            _capability('V', 'Intersite V', 'model_hamiltonian.parameter', metadata={'scopes': ['bond', 'global', 'sweep']}),
            _capability('epsilon', 'On-site epsilon', 'model_hamiltonian.parameter', metadata={'scopes': ['site', 'global', 'sweep']}),
            _capability('nelec', 'Electron count', 'model_hamiltonian.parameter', metadata={'scopes': ['global', 'sweep']}),
            _capability(
                'spin_multiplicity',
                'Target spin multiplicity',
                'model_hamiltonian.parameter',
                metadata={
                    'scopes': ['global', 'sweep'],
                    'constraint': 'spin_multiplicity = |nalpha-nbeta| + 1',
                    'meaning': 'Highest-weight fixed-spin sector; approximate references may still require spin-purity diagnostics.',
                },
            ),
            _capability('boundary', 'Boundary condition', 'model_hamiltonian.parameter', metadata={'scopes': ['global', 'sweep']}),
            _capability(
                'representation',
                'Hamiltonian representation',
                'model_hamiltonian.parameter',
                planner_allowed=False,
                metadata={'scopes': ['bloch'], 'values': ['finite_cluster', 'bloch']},
            ),
            _capability(
                'lattice_vectors',
                'Primitive lattice vectors',
                'model_hamiltonian.parameter',
                planner_allowed=False,
                metadata={'scopes': ['bloch']},
            ),
            _capability(
                'cell_offset',
                'Bond cell offset',
                'model_hamiltonian.parameter',
                planner_allowed=False,
                metadata={'scopes': ['bloch'], 'applies_to': 'bond'},
            ),
            _capability(
                'electrons_per_cell',
                'Electrons per primitive cell',
                'model_hamiltonian.parameter',
                planner_allowed=False,
                metadata={'scopes': ['bloch']},
            ),
            _capability(
                'kmesh',
                'Bloch k-point mesh',
                'model_hamiltonian.parameter',
                planner_allowed=False,
                metadata={'scopes': ['bloch']},
            ),
            _capability(
                'effective_t',
                'Effective hopping t',
                'model_hamiltonian.parameter',
                planner_allowed=False,
                backend_allowed=False,
                metadata={'scopes': ['bond']},
            ),
            _capability(
                'effective_V',
                'Effective intersite V',
                'model_hamiltonian.parameter',
                planner_allowed=False,
                backend_allowed=False,
                metadata={'scopes': ['bond']},
            ),
        ],
        'model_hamiltonian_operations': [
            _capability('set_global_parameter', 'Set global parameter', 'model_hamiltonian.operation'),
            _capability('set_site_parameter', 'Set site parameter', 'model_hamiltonian.operation'),
            _capability('shift_site_parameter', 'Shift site parameter', 'model_hamiltonian.operation'),
            _capability('scale_site_parameter', 'Scale site parameter', 'model_hamiltonian.operation'),
            _capability('add_site_defect', 'Add site defect', 'model_hamiltonian.operation'),
            _capability('set_bond_parameter', 'Set bond parameter', 'model_hamiltonian.operation'),
            _capability('shift_bond_parameter', 'Shift bond parameter', 'model_hamiltonian.operation'),
            _capability('scale_bond_parameter', 'Scale bond parameter', 'model_hamiltonian.operation'),
            _capability('add_bond_defect', 'Add bond defect', 'model_hamiltonian.operation'),
            _capability('change_nelec', 'Change electron count', 'model_hamiltonian.operation'),
            _capability('change_boundary', 'Change boundary', 'model_hamiltonian.operation'),
            _capability('change_solver', 'Change solver', 'model_hamiltonian.operation'),
        ],
        'model_hamiltonian_observables': [
            _capability(
                'energy',
                'Total energy',
                'model_hamiltonian.observable',
                metadata={
                    'result_field': 'energy',
                    'requestable_output': True,
                    'assistant_ui_output': False,
                    'result_shape': 'scalar',
                    'unit': 'energy',
                    'supports_plot': ['line_plot', 'scatter_plot', 'heatmap'],
                },
            ),
            _capability(
                'reference_energy',
                'Reference energy',
                'model_hamiltonian.observable',
                metadata={
                    'result_field': 'reference_energy',
                    'requires_solver': ['mp2', 'ccsd', 'ccsd_t', 'fci', 'block2_dmrg'],
                    'result_shape': 'scalar',
                    'unit': 'energy',
                    'supports_plot': ['line_plot', 'scatter_plot', 'heatmap'],
                },
            ),
            _capability(
                'energy_per_site',
                'Energy per site',
                'model_hamiltonian.observable',
                metadata={
                    'result_field': 'energy_per_site',
                    'requires_solver': ['dmet'],
                    'result_shape': 'scalar',
                    'unit': 'energy_per_site',
                    'supports_plot': ['line_plot', 'scatter_plot', 'heatmap'],
                    'generated_output_rule': 'DMET reports its size-normalized energy alongside the total lattice energy.',
                },
            ),
            _capability(
                'entanglement_diagnostics',
                'Orbital entanglement diagnostics',
                'model_hamiltonian.observable',
                metadata={
                    'result_field': 'entanglement_diagnostics',
                    'requestable_output': True,
                    'assistant_ui_output': True,
                    'requires_solver': ['block2_dmrg'],
                    'result_shape': 'diagnostic_summary',
                    'unit': 'dimensionless',
                    'artifact_kinds': ['block2_dmrg_result', 'block2_dmrg_arrays'],
                    'generated_output_rule': 'block2 DMRG reports ground-state single-orbital entropy and bipartite entropy while limiting NPDM construction to the 2-RDM.',
                },
            ),
            _capability(
                'excited_states',
                'Low-lying state energies',
                'model_hamiltonian.observable',
                metadata={
                    'result_fields': [
                        'state_energies',
                        'excitation_energies',
                        'requested_root_count',
                        'computed_root_count',
                        'targeted_roots_complete',
                        'state_sector',
                    ],
                    'requestable_output': True,
                    'assistant_ui_output': True,
                    'requires_solver': ['fci', 'block2_dmrg'],
                    'result_shape': 'state_vector',
                    'unit': 'energy',
                    'generated_output_rule': 'FCI and block2 DMRG return the requested low-energy roots; these targeted roots are not a complete many-body spectrum.',
                },
                limitations=['Transition RDMs are not implemented; cross-case root identity is inferred from one-particle density matrices or natural occupations and ambiguous assignments require review.'],
            ),
            _capability(
                'symmetry_analysis',
                'State symmetry analysis',
                'model_hamiltonian.observable',
                metadata={
                    'result_field': 'symmetry_analysis',
                    'requestable_output': True,
                    'assistant_ui_output': True,
                    'requires_solver': ['fci', 'block2_dmrg'],
                    'result_shape': 'diagnostic_summary',
                    'unit': 'dimensionless',
                    'generated_output_rule': 'FCI and block2 DMRG report particle number, spin sector, and spin-square information when requested.',
                },
            ),
            _capability(
                'energy_level_count',
                'Energy level count',
                'model_hamiltonian.observable',
                metadata={
                    'result_field': 'energy_level_count',
                    'result_shape': 'scalar',
                    'unit': 'count',
                    'artifact_kinds': [
                        'model_hamiltonian_energy_levels',
                        'model_hamiltonian_energy_levels_txt',
                    ],
                },
            ),
            _capability(
                'many_body_basis_dimension',
                'Many-body basis dimension',
                'model_hamiltonian.observable',
                metadata={'result_field': 'many_body_basis_dimension', 'result_shape': 'scalar', 'unit': 'count'},
            ),
            _capability(
                'strong_correlation_diagnostics',
                'Strong correlation diagnostics',
                'model_hamiltonian.observable',
                limitations=['Heuristic finite-size diagnostics; not a thermodynamic-limit phase-boundary classifier.'],
                metadata={
                    'result_field': 'strong_correlation_diagnostics',
                    'requestable_output': True,
                    'result_shape': 'diagnostic_summary',
                    'unit': 'dimensionless',
                    'derived_from': [
                        'U/t',
                        'V/t',
                        'correlation_energy',
                        'mean_field_gap',
                        'frontier_orbital_degeneracy',
                        'natural_occupations',
                        'max_double_excitation_amplitude',
                        'solver_convergence',
                        'gap',
                        'double_occupancy',
                        'spin_correlation',
                        'charge_correlation',
                        'local_magnetization',
                        'sublattice_order_parameters',
                        'nearest_neighbor_one_body_coherence',
                    ],
                    'summary_fields': [
                        'level',
                        'level_reason',
                        'score',
                        'physics_score',
                        'physics_level',
                        'solver_stress_score',
                        'solver_stress_level',
                        'confidence',
                        'internal_quantities',
                        'parameter_summary',
                        'diagnostics',
                        'evidence_groups',
                        'method_recommendation',
                    ],
                    'comparison_summary_fields': [
                        'final_energy',
                        'energy_per_site',
                        'reference_energy',
                        'filling',
                        'gap',
                        'mean_field_gap',
                        'natural_occupation_fractionality',
                        'fractional_natural_orbital_count',
                        'max_double_excitation_amplitude',
                        'mean_double_occupancy',
                        'nearest_neighbor_spin_correlation',
                        'nearest_neighbor_charge_correlation',
                        'sublattice_charge_imbalance',
                        'staggered_magnetization',
                        'mean_nearest_neighbor_one_body_coherence',
                        'energy_over_abs_t',
                        'energy_per_site_over_abs_t',
                    ],
                    'internal_quantities': {
                        'mean_field_gap': {'result_shape': 'scalar', 'unit': 'energy', 'derived_from': 'reference_orbitals'},
                        'frontier_orbital_degeneracy': {
                            'result_shape': 'diagnostic_summary',
                            'unit': 'energy_spacing',
                            'derived_from': 'reference_orbitals',
                        },
                        'natural_occupations': {'result_shape': 'array', 'unit': 'electron', 'derived_from': 'one_particle_density_matrix'},
                        'max_double_excitation_amplitude': {
                            'result_shape': 'scalar',
                            'unit': 'dimensionless',
                            'derived_from': 'MP2/CCSD T2 amplitudes',
                        },
                        'gap': {'result_shape': 'scalar', 'unit': 'energy', 'derived_from': 'energy_levels'},
                        'density': {'result_shape': 'site_vector', 'operator': 'n_i_up + n_i_down'},
                        'local_magnetization': {
                            'result_shape': 'site_vector',
                            'operator': 'n_i_up - n_i_down',
                        },
                        'double_occupancy': {'result_shape': 'site_vector', 'operator': 'n_i_up n_i_down'},
                        'spin_correlation': {'result_shape': 'pair_matrix', 'operator': 'S_i dot S_j'},
                        'charge_correlation': {
                            'result_shape': 'pair_matrix',
                            'operator': '(n_i - <n_i>)(n_j - <n_j>)',
                        },
                        'sublattice_order_parameters': {
                            'result_shape': 'diagnostic_summary',
                            'unit': 'dimensionless',
                            'derived_from': 'site-resolved density and magnetization',
                        },
                        'nearest_neighbor_one_body_coherence': {
                            'result_shape': 'scalar',
                            'unit': 'dimensionless',
                            'derived_from': 'one_particle_density_matrix',
                        },
                    },
                    'requires_solver': ['mp2', 'ccsd', 'ccsd_t', 'fci', 'block2_dmrg', 'dmet'],
                    'artifact_kinds': ['strong_correlation_diagnostics'],
                    'execution_status_policy': {
                        'failed': 'strong_solver_stress',
                        'unconverged': 'strong_solver_stress',
                        'blocked': 'not_correlation_evidence',
                    },
                    'generated_output_rule': (
                        'Strong correlation diagnostics are the single user-facing model-Hamiltonian analysis output. '
                        'Mean-field gap, natural occupations, T2 amplitudes, gap, double occupancy, spin correlation, '
                        'and charge correlation are internal diagnostic ingredients and should not be advertised as '
                        'separate requestable outputs. Scalar diagnostic fields may be flattened into planner '
                        'comparison tables and postprocessing options only when present in executed results.'
                    ),
                },
            ),
            _capability(
                'structure_factor',
                'Structure factor',
                'model_hamiltonian.observable',
                CAPABILITY_PLANNED,
                planner_allowed=False,
                backend_allowed=False,
                limitations=['Derived from spin or charge correlation matrices plus lattice geometry; planned as postprocessing.'],
                metadata={'result_shape': 'q_vector', 'unit': 'dimensionless', 'derived_from': ['spin_correlation', 'charge_correlation']},
            ),
            _capability(
                'bloch_band_metrics',
                'Bloch band metrics',
                'model_hamiltonian.observable',
                planner_allowed=False,
                metadata={
                    'result_fields': ['band_gap', 'direct_gap', 'fermi_energy', 'bandwidth'],
                    'requestable_output': False,
                    'result_shape': 'scalar',
                    'unit': 'energy',
                    'summary_fields': ['band_gap', 'direct_gap', 'fermi_energy', 'bandwidth', 'is_metal'],
                    'generated_output_rule': 'The Bloch tight-binding solver always reports zero-temperature band metrics.',
                },
            ),
            _capability(
                'bloch_band_structure',
                'Bloch band structure',
                'model_hamiltonian.observable',
                planner_allowed=False,
                metadata={
                    'result_field': 'bloch_band_structure',
                    'requestable_output': False,
                    'compact_result': False,
                    'result_shape': 'kpath_bands',
                    'artifact_kinds': ['model_bloch_bands', 'model_bloch_bands_tsv'],
                },
            ),
            _capability(
                'bloch_dos',
                'Bloch density of states',
                'model_hamiltonian.observable',
                planner_allowed=False,
                metadata={
                    'result_field': 'bloch_dos',
                    'requestable_output': False,
                    'compact_result': False,
                    'result_shape': 'energy_density_series',
                    'artifact_kinds': ['model_bloch_dos', 'model_bloch_dos_tsv'],
                },
            ),
            _capability(
                'bloch_kmesh',
                'Bloch k-mesh eigenvalues and occupations',
                'model_hamiltonian.observable',
                planner_allowed=False,
                metadata={
                    'result_field': 'bloch_kmesh',
                    'requestable_output': False,
                    'compact_result': False,
                    'result_shape': 'kmesh_bands',
                    'artifact_kinds': ['model_bloch_kmesh', 'model_bloch_kmesh_tsv'],
                },
            ),
            _capability(
                'bloch_hamiltonian_samples',
                'Bloch Hamiltonian samples',
                'model_hamiltonian.observable',
                planner_allowed=False,
                metadata={
                    'result_field': 'bloch_hamiltonian_samples',
                    'requestable_output': False,
                    'compact_result': False,
                    'result_shape': 'complex_matrix_samples',
                    'artifact_kinds': ['model_bloch_hamiltonian_samples'],
                },
            ),
            _capability(
                'interaction_treatment',
                'Bloch interaction treatment',
                'model_hamiltonian.observable',
                planner_allowed=False,
                metadata={
                    'result_field': 'interaction_treatment',
                    'requestable_output': False,
                    'result_shape': 'method_contract',
                },
            ),
        ],
    }


__all__ = ['build_model_hamiltonian_families']
