from __future__ import annotations

from typing import Any, Callable, Dict, List


def build_molecular_families(
    item_factory: Callable[..., Any],
    *,
    capability_design_only: str,
    capability_planned: str,
) -> Dict[str, List[Any]]:
    _capability = item_factory
    CAPABILITY_DESIGN_ONLY = capability_design_only
    CAPABILITY_PLANNED = capability_planned

    molecular_basis_sets = [
        ('sto-3g', 'STO-3G', 'minimal'),
        ('minao', 'MINAO', 'minimal'),
        ('3-21g', '3-21G', 'pople'),
        ('4-31g', '4-31G', 'pople'),
        ('6-31g', '6-31G', 'pople'),
        ('6-31g*', '6-31G*', 'pople'),
        ('6-31g**', '6-31G**', 'pople'),
        ('6-31+g', '6-31+G', 'pople'),
        ('6-31++g', '6-31++G', 'pople'),
        ('6-31+g*', '6-31+G*', 'pople'),
        ('6-31++g**', '6-31++G**', 'pople'),
        ('6-311g', '6-311G', 'pople'),
        ('6-311g*', '6-311G*', 'pople'),
        ('6-311g**', '6-311G**', 'pople'),
        ('6-311+g', '6-311+G', 'pople'),
        ('6-311++g', '6-311++G', 'pople'),
        ('6-311+g*', '6-311+G*', 'pople'),
        ('6-311++g**', '6-311++G**', 'pople'),
        ('cc-pvdz', 'cc-pVDZ', 'dunning'),
        ('cc-pvtz', 'cc-pVTZ', 'dunning'),
        ('cc-pvqz', 'cc-pVQZ', 'dunning'),
        ('cc-pv5z', 'cc-pV5Z', 'dunning'),
        ('aug-cc-pvdz', 'aug-cc-pVDZ', 'dunning'),
        ('aug-cc-pvtz', 'aug-cc-pVTZ', 'dunning'),
        ('aug-cc-pvqz', 'aug-cc-pVQZ', 'dunning'),
        ('aug-cc-pv5z', 'aug-cc-pV5Z', 'dunning'),
        ('cc-pcvdz', 'cc-pCVDZ', 'dunning-core-valence'),
        ('cc-pcvtz', 'cc-pCVTZ', 'dunning-core-valence'),
        ('cc-pcvqz', 'cc-pCVQZ', 'dunning-core-valence'),
        ('aug-cc-pcvdz', 'aug-cc-pCVDZ', 'dunning-core-valence'),
        ('aug-cc-pcvtz', 'aug-cc-pCVTZ', 'dunning-core-valence'),
        ('aug-cc-pcvqz', 'aug-cc-pCVQZ', 'dunning-core-valence'),
        ('cc-pwcvdz', 'cc-pwCVDZ', 'dunning-core-valence'),
        ('cc-pwcvtz', 'cc-pwCVTZ', 'dunning-core-valence'),
        ('aug-cc-pwcvdz', 'aug-cc-pwCVDZ', 'dunning-core-valence'),
        ('aug-cc-pwcvtz', 'aug-cc-pwCVTZ', 'dunning-core-valence'),
        ('def2-svp', 'def2-SVP', 'def2'),
        ('def2-svpd', 'def2-SVPD', 'def2'),
        ('def2-tzvp', 'def2-TZVP', 'def2'),
        ('def2-tzvpp', 'def2-TZVPP', 'def2'),
        ('def2-tzvpd', 'def2-TZVPD', 'def2'),
        ('def2-tzvppd', 'def2-TZVPPD', 'def2'),
        ('def2-qzvp', 'def2-QZVP', 'def2'),
        ('def2-qzvpp', 'def2-QZVPP', 'def2'),
        ('def2-qzvpd', 'def2-QZVPD', 'def2'),
        ('def2-qzvppd', 'def2-QZVPPD', 'def2'),
        ('ano', 'ANO', 'ano'),
        ('ano-rcc', 'ANO-RCC', 'ano'),
        ('lanl2dz', 'LANL2DZ', 'ecp'),
        ('lanl2tz', 'LANL2TZ', 'ecp'),
        ('lanl08', 'LANL08', 'ecp'),
    ]

    molecular_reference_policies = {
        'hf': {
            'closed_shell_default': 'rhf', 'open_shell_default': 'uhf',
            'unrestricted': 'uhf', 'allowed': ['rhf', 'uhf'], 'restricted_open_shell': 'unsupported',
        },
        'dft': {
            'closed_shell_default': 'rks', 'open_shell_default': 'uks',
            'unrestricted': 'uks', 'allowed': ['rks', 'uks'], 'restricted_open_shell': 'unsupported',
        },
        'mp2': {
            'closed_shell_default': 'rhf', 'open_shell_default': 'uhf',
            'unrestricted': 'uhf', 'allowed': ['rhf', 'uhf'], 'restricted_open_shell': 'unsupported',
        },
        'ccsd': {
            'closed_shell_default': 'rhf', 'open_shell_default': 'uhf',
            'unrestricted': 'uhf', 'allowed': ['rhf', 'uhf'], 'restricted_open_shell': 'unsupported',
        },
        'ccsd_t': {
            'closed_shell_default': 'rhf', 'open_shell_default': 'uhf',
            'unrestricted': 'uhf', 'allowed': ['rhf', 'uhf'], 'restricted_open_shell': 'unsupported',
        },
        'fci': {
            'closed_shell_default': 'rhf', 'open_shell_default': 'uhf',
            'unrestricted': 'uhf', 'allowed': ['rhf', 'uhf'], 'restricted_open_shell': 'unsupported',
        },
        'casci': {
            'closed_shell_default': 'rhf', 'open_shell_default': 'rohf',
            'unrestricted': 'uhf', 'allowed': ['rhf', 'rohf', 'uhf'], 'restricted_open_shell': 'rohf',
        },
        'casscf': {
            'closed_shell_default': 'rhf', 'open_shell_default': 'rohf',
            'unrestricted': 'uhf', 'allowed': ['rhf', 'rohf', 'uhf'], 'restricted_open_shell': 'rohf',
        },
    }

    cas_request_contract = {
        'requires_active_space': ['ncas', 'nelecas', 'approved'],
    }

    return {
        'molecular_methods': [
            _capability(
                'hf',
                'Hartree-Fock',
                'molecular.method',
                metadata={
                    'aliases': ['hartree-fock', 'hartree fock', 'hartreefock'],
                    'reference_policy': molecular_reference_policies['hf'],
                },
            ),
            _capability(
                'dft',
                'Density functional theory',
                'molecular.method',
                metadata={
                    'aliases': ['ks-dft', 'kohn-sham', 'kohn sham'],
                    'reference_policy': molecular_reference_policies['dft'],
                },
            ),
            _capability('mp2', 'MP2', 'molecular.method', metadata={'reference_policy': molecular_reference_policies['mp2']}),
            _capability(
                'ccsd',
                'CCSD',
                'molecular.method',
                metadata={
                    'reference_policy': molecular_reference_policies['ccsd'],
                },
            ),
            _capability(
                'ccsd_t',
                'CCSD(T)',
                'molecular.method',
                metadata={
                    'aliases': ['ccsd(t)', 'ccsd-t', 'ccsdt', 'ccsd triples'],
                    'reference_policy': molecular_reference_policies['ccsd_t'],
                    'result_field': 'triples_correction',
                    'result_shape': 'scalar',
                    'unit': 'Hartree',
                    'generated_output_rule': 'CCSD(T) produces a perturbative triples correction when the triples_correction field is present.',
                },
            ),
            _capability(
                'fci',
                'Full CI',
                'molecular.method',
                metadata={
                    'aliases': ['full-ci', 'full ci', 'fullci'],
                    'reference_policy': molecular_reference_policies['fci'],
                    'state_targets': {
                        'options': ['nroots'],
                        'default_nroots': 1,
                        'result_fields': ['state_energies', 'excitation_energies'],
                    },
                },
            ),
            _capability(
                'casci',
                'CASCI',
                'molecular.method',
                limitations=[
                    'Requires explicit approved active_space.ncas and active_space.nelecas.',
                    'Automatic CAS uses a UHF orbital reference followed by spin-adapted RHF/ROHF-style execution; unrestricted CAS is an explicit advanced path.',
                    'Unrestricted CAS supports either a shared active orbital index list or spin-resolved alpha/beta lists.',
                ],
                metadata={
                    'aliases': [
                        'cas-ci',
                        'cas ci',
                        'complete-active-space-ci',
                        'complete active space ci',
                    ],
                    'result_field': 'cas_result',
                    'reference_policy': molecular_reference_policies['casci'],
                    'initial_reference_policy': {'default': 'uhf'},
                    'request_contract': cas_request_contract,
                    'result_shape': 'method_result',
                    'unit': 'Hartree',
                    'summary_fields': ['energy', 'converged', 'initial_reference', 'cas_reference', 'spin_adapted', 'ncas', 'nelecas', 'active_orbital_indices', 'natural_occupations'],
                    'state_targets': {
                        'options': ['nroots'],
                        'default_nroots': 1,
                        'mode': 'fixed_orbital_multi_root',
                    },
                    'artifact_kinds': ['cas_result'],
                    'generated_output_rule': 'CASCI produces a CAS result when the cas_result field is present.',
                },
            ),
            _capability(
                'casscf',
                'CASSCF',
                'molecular.method',
                limitations=[
                    'Requires explicit approved active_space.ncas and active_space.nelecas.',
                    'Automatic CAS uses a UHF orbital reference followed by spin-adapted RHF/ROHF-style execution; unrestricted CAS is an explicit advanced path.',
                    'Unrestricted CAS supports either a shared active orbital index list or spin-resolved alpha/beta lists.',
                ],
                metadata={
                    'aliases': [
                        'cas-scf',
                        'cas scf',
                        'cas-sc-f',
                        'complete-active-space-scf',
                        'complete active space scf',
                    ],
                    'result_field': 'cas_result',
                    'reference_policy': molecular_reference_policies['casscf'],
                    'initial_reference_policy': {'default': 'uhf'},
                    'request_contract': cas_request_contract,
                    'result_shape': 'method_result',
                    'unit': 'Hartree',
                    'summary_fields': ['energy', 'converged', 'initial_reference', 'cas_reference', 'spin_adapted', 'ncas', 'nelecas', 'active_orbital_indices', 'natural_occupations'],
                    'state_targets': {
                        'options': ['nroots', 'state_average_weights'],
                        'default_nroots': 1,
                        'mode': 'state_averaged_when_nroots_exceeds_one',
                    },
                    'artifact_kinds': ['cas_result'],
                    'generated_output_rule': 'CASSCF produces a CAS result when the cas_result field is present.',
                },
            ),
        ],
        'molecular_jobs': [
            _capability('single_point', 'Single point energy', 'molecular.job'),
            _capability(
                'molecular_dynamics',
                'Molecular dynamics trajectory',
                'molecular.job',
                description=(
                    'Run one Born-Oppenheimer molecular-dynamics trajectory; '
                    'sampled frames remain artifacts owned by the task.'
                ),
                limitations=[
                    'The executable slice supports NVE trajectories with restricted B3LYP/def2-SVP and explicit qh9 or qh9_relaxed_scf profiles for H/C/N/O/F molecules.',
                    'A trajectory is one Task; sampled frames are not independent Study cases.',
                    'Mid-trajectory restart is not yet part of the executable contract.',
                ],
                ui_visibility='hidden',
                required_provider_ids=('provider.pyscf',),
                metadata={
                    'task_spec_field': 'molecular_dynamics',
                    'profiles': {
                        'qh9': {
                            'method': 'dft', 'basis': 'def2-svp', 'xc': 'b3lyp',
                            'runtime': {'conv_tol': 1e-13, 'conv_tol_grad': 3.16e-5, 'grid_level': 3, 'diis_space': 8},
                        },
                        'qh9_relaxed_scf': {
                            'method': 'dft', 'basis': 'def2-svp', 'xc': 'b3lyp',
                            'runtime': {'conv_tol': 1e-8, 'conv_tol_grad': 3.16e-5, 'grid_level': 3, 'diis_space': 8},
                        },
                    },
                    'artifact_kinds': [
                        'molecular_md_manifest',
                        'molecular_md_frame_arrays',
                        'molecular_md_failure',
                    ],
                    'request_contract': {
                        'profiles': ['qh9', 'qh9_relaxed_scf'],
                        'ensembles': ['nve'],
                        'methods': ['dft'],
                        'basis_sets': ['def2-svp'],
                        'ao_conventions': ['qh9'],
                    },
                },
            ),
        ],
        'molecular_observables': [
            _capability(
                'trajectory',
                'Molecular dynamics trajectory',
                'molecular.observable',
                description='Compact trajectory summary with typed references to sampled frame arrays.',
                ui_visibility='hidden',
                metadata={
                    'result_field': 'trajectory',
                    'requestable_output': True,
                    'assistant_ui_output': False,
                    'result_shape': 'trajectory_summary',
                    'unit': 'mixed_atomic_units',
                    'summary_fields': [
                        'ensemble',
                        'steps_completed',
                        'sampled_frame_count',
                        'temperature_kelvin',
                        'time_step_au',
                    ],
                    'artifact_kinds': [
                        'molecular_md_manifest',
                        'molecular_md_frame_arrays',
                    ],
                    'generated_output_rule': 'A molecular-dynamics task produces a trajectory summary and sampled-frame artifacts.',
                },
            ),
            _capability(
                'energy',
                'Total energy',
                'molecular.observable',
                metadata={
                    'result_field': 'energy',
                    'requestable_output': True,
                    'assistant_ui_output': False,
                    'result_shape': 'scalar',
                    'unit': 'Hartree',
                    'generated_output_rule': 'Total energy is a generated molecular observable when the energy field is present.',
                },
            ),
            _capability(
                'ccsd_labels',
                'Paired HF and CCSD labels',
                'molecular.observable',
                description='HF Fock, CCSD spin-summed unrelaxed 1-RDM, overlap and paired total energies in QH9 AO order.',
                metadata={
                    'result_field': 'ccsd_labels',
                    'requestable_output': True,
                    'assistant_ui_output': True,
                    'result_shape': 'artifact_summary',
                    'artifact_kinds': ['ccsd_label_arrays', 'ccsd_label_manifest'],
                    'generated_output_rule': 'Requested RHF/CCSD def2-SVP labels require converged HF, CCSD and Lambda equations.',
                },
                limitations=['Molecular restricted all-electron CCSD/def2-SVP single points for H/C/N/O/F; no density fitting.'],
            ),
            _capability(
                'homo_lumo',
                'HOMO-LUMO summary',
                'molecular.observable',
                metadata={
                    'result_fields': ['homo', 'lumo', 'gap'],
                    'requestable_output': True,
                    'assistant_ui_output': False,
                    'result_shape': 'scalar_group',
                    'unit': 'Hartree',
                    'generated_output_rule': 'HOMO, LUMO, and gap are generated molecular observables when their fields are present.',
                },
            ),
            _capability(
                'dipole',
                'Dipole moment',
                'molecular.observable',
                metadata={
                    'result_field': 'dipole',
                    'requestable_output': True,
                    'assistant_ui_output': False,
                    'result_shape': 'vector3',
                    'unit': 'Debye',
                    'generated_output_rule': 'Dipole moment is a generated molecular observable when the dipole field is present.',
                },
            ),
            _capability(
                'reference_energy',
                'Reference energy',
                'molecular.observable',
                metadata={
                    'result_field': 'reference_energy',
                    'result_shape': 'scalar',
                    'unit': 'Hartree',
                    'generated_output_rule': 'Reference energy is generated by the reference SCF stage when the reference_energy field is present.',
                },
            ),
            _capability(
                'entanglement_diagnostics',
                'Orbital entanglement diagnostics',
                'molecular.observable',
                metadata={
                    'result_field': 'entanglement_diagnostics',
                    'requestable_output': True,
                    'assistant_ui_output': True,
                    'requires_solver': ['block2_dmrg'],
                    'result_shape': 'diagnostic_summary',
                    'unit': 'dimensionless',
                    'artifact_kinds': ['block2_dmrg_result', 'block2_dmrg_arrays'],
                    'generated_output_rule': 'block2 DMRG reports ground-state single-orbital entropy and bipartite entropy while limiting NPDM construction to the 2-RDM.',
                },
            ),
            _capability(
                'excited_states',
                'Low-lying molecular states',
                'molecular.observable',
                metadata={
                    'result_fields': [
                        'state_energies',
                        'excitation_energies',
                        'requested_root_count',
                        'computed_root_count',
                        'targeted_roots_complete',
                        'state_sector',
                        'state_average_energy',
                        'state_average_weights',
                        'orbital_optimization_mode',
                    ],
                    'requestable_output': True,
                    'assistant_ui_output': True,
                    'requires_solver': ['fci', 'block2_dmrg'],
                    'result_shape': 'state_vector',
                    'unit': 'Hartree',
                    'generated_output_rule': 'Molecular FCI, CASCI, and CASSCF return requested low-energy roots; multi-root CASSCF uses state-averaged orbital optimization.',
                },
                limitations=[
                    'Roots belong to the selected particle, spin, and configured symmetry sector; other sectors are not searched automatically.',
                    'Transition RDMs are not implemented; cross-case root identity is inferred from one-particle density matrices or natural occupations and ambiguous assignments require review.',
                ],
            ),
            _capability(
                'symmetry_analysis',
                'DMRG symmetry analysis',
                'molecular.observable',
                metadata={
                    'result_field': 'symmetry_analysis',
                    'requestable_output': True,
                    'assistant_ui_output': True,
                    'requires_solver': ['block2_dmrg'],
                    'result_shape': 'diagnostic_summary',
                    'unit': 'dimensionless',
                    'generated_output_rule': 'block2 DMRG reports particle number, spin sector, spin-square expectation, and orbital-symmetry metadata when requested.',
                },
            ),
        ],
        'molecular_basis_sets': [
            _capability(
                basis_id,
                label,
                'molecular.basis',
                metadata={'family': family},
            )
            for basis_id, label, family in molecular_basis_sets
        ],
        'molecular_auxbasis_sets': [
            _capability(
                'weigend+etb',
                'weigend+etb',
                'molecular.auxbasis',
                metadata={'scopes': ['scf', 'casscf'], 'basis_families': ['general'], 'fallback': True},
            ),
            _capability(
                'def2-universal-jkfit',
                'def2-universal-jkfit',
                'molecular.auxbasis',
                metadata={'scopes': ['scf', 'casscf'], 'basis_families': ['def2', 'pople', 'minimal', 'general'], 'fallback': True},
            ),
            _capability(
                'def2-svp-jkfit',
                'def2-svp-jkfit',
                'molecular.auxbasis',
                metadata={'scopes': ['scf', 'casscf'], 'recommended_for_basis': ['sto-3g', '3-21g', 'def2-svp', 'def2-svpd']},
            ),
            _capability(
                'def2-tzvp-jkfit',
                'def2-tzvp-jkfit',
                'molecular.auxbasis',
                metadata={'scopes': ['scf', 'casscf'], 'recommended_for_basis': ['def2-tzvp']},
            ),
            _capability(
                'def2-qzvp-jkfit',
                'def2-qzvp-jkfit',
                'molecular.auxbasis',
                metadata={'scopes': ['scf', 'casscf'], 'recommended_for_basis': ['def2-qzvp']},
            ),
            _capability(
                'cc-pvdz-jkfit',
                'cc-pvdz-jkfit',
                'molecular.auxbasis',
                metadata={'scopes': ['scf', 'casscf'], 'recommended_for_basis': ['6-31g', '6-31g*', 'cc-pvdz']},
            ),
            _capability(
                'cc-pvtz-jkfit',
                'cc-pvtz-jkfit',
                'molecular.auxbasis',
                metadata={'scopes': ['scf', 'casscf'], 'recommended_for_basis': ['6-311g', 'cc-pvtz']},
            ),
            _capability(
                'aug-cc-pvdz-jkfit',
                'aug-cc-pvdz-jkfit',
                'molecular.auxbasis',
                metadata={'scopes': ['scf', 'casscf'], 'recommended_for_basis': ['6-31++g', 'aug-cc-pvdz']},
            ),
            _capability(
                'heavy-aug-cc-pvdz-jkfit',
                'heavy-aug-cc-pvdz-jkfit',
                'molecular.auxbasis',
                metadata={'scopes': ['scf', 'casscf'], 'recommended_for_basis': ['6-31+g']},
            ),
        ],
        'molecular_xc_functionals': [
            _capability('cam-b3lyp', 'CAM-B3LYP', 'molecular.xc'),
            _capability('wb97x-d', 'wB97X-D', 'molecular.xc'),
            _capability('wb97x', 'wB97X', 'molecular.xc'),
            _capability('m06-2x', 'M06-2X', 'molecular.xc'),
            _capability('b3lyp', 'B3LYP', 'molecular.xc'),
            _capability('pbe0', 'PBE0', 'molecular.xc'),
            _capability('m06', 'M06', 'molecular.xc'),
            _capability('blyp', 'BLYP', 'molecular.xc'),
            _capability('bp86', 'BP86', 'molecular.xc'),
            _capability('pbe', 'PBE', 'molecular.xc'),
            _capability('lda', 'LDA', 'molecular.xc'),
        ],
        'molecular_workflow_options': [
            _capability(
                'density_fitting',
                'Density fitting',
                'molecular.workflow_option',
                metadata={
                    'task_spec_field': 'density_fitting',
                    'result_field': 'density_fitting',
                    'summary_fields': ['enabled', 'auxbasis', 'apply_to', 'applied_to', 'resolved_auxbasis', 'casscf_implementation'],
                    'apply_to': ['scf', 'scf_and_casscf'],
                    'default': False,
                    'generated_output_rule': 'Density fitting metadata is a generated workflow result when the density_fitting field is present.',
                },
                limitations=['SCF+CASSCF fitting supports restricted and ROHF CASSCF with FCI or block2. Legacy SCF scope on restricted CASSCF is normalized to scf_and_casscf. Unrestricted CASSCF and block2 CASCI do not support DF active-space integrals.'],
            ),
            _capability(
                'orbital_processing',
                'Orbital processing',
                'molecular.workflow_option',
                metadata={'task_spec_field': 'orbital_processing'},
            ),
            _capability(
                'active_space',
                'Active-space setup',
                'molecular.workflow_option',
                metadata={
                    'task_spec_field': 'active_space',
                    'result_field': 'active_space',
                    'result_shape': 'workflow_contract',
                    'summary_fields': ['enabled', 'selection_method', 'ncas', 'nelecas', 'orbital_indices', 'approved', 'rationale', 'audit_summary'],
                    'artifact_kinds': ['active_space', 'active_space_summary_table', 'active_space_audit', 'active_space_audit_table'],
                    'generated_output_rule': 'Active-space proposals and approved contracts are generated workflow outputs when the active_space field is present; ActiveSpaceAudit may contain manual, UNO, AVAS, and merged candidates.',
                },
            ),
            _capability(
                'sc_nevpt2',
                'SC-NEVPT2 post-CAS correction',
                'molecular.workflow_option',
                limitations=[
                    'Requires method=casci or method=casscf with an approved active-space contract.',
                    'Current backend supports spin-adapted restricted/ROHF-style CAS references; unrestricted CAS is blocked for SC-NEVPT2.',
                    'Current backend supports the ground-state correction only: post_cas.sc_nevpt2.root must be 0.',
                ],
                metadata={
                    'task_spec_field': 'post_cas.sc_nevpt2',
                    'request_contract': {
                        'requires_methods': ['casci', 'casscf'],
                        'requires_active_space_approval': True,
                        'allowed_references': ['rhf', 'rohf'],
                        'allowed_roots': [0],
                    },
                    'result_field': 'post_cas_results',
                    'result_shape': 'post_cas_correction',
                    'unit': 'Hartree',
                    'summary_fields': ['correction_energy', 'total_energy', 'root', 'density_fit', 'reference'],
                    'artifact_kinds': ['sc_nevpt2'],
                    'generated_output_rule': 'SC-NEVPT2 produces a post-CAS correction when post_cas_results.sc_nevpt2 is present.',
                },
            ),
            _capability(
                'correlation_diagnostics',
                'Correlation diagnostics',
                'molecular.workflow_option',
                description='Automatically generated molecular strong-correlation diagnostic summary.',
                ui_visibility='hidden',
                metadata={
                    'result_field': 'correlation_diagnostics',
                    'result_shape': 'diagnostic_summary',
                    'summary_fields': [
                        'homo',
                        'lumo',
                        'gap',
                        'spin_square',
                        'warnings',
                        'fractional_occupations',
                        'recommended_next_steps',
                        'molecular_correlation_risk',
                        'physics_level',
                        'solver_stress_level',
                        'routing_level',
                        'routing_reason',
                        'score',
                        'level',
                        'confidence',
                    ],
                    'artifact_kinds': ['correlation_diagnostics'],
                    'diagnostic_contract': {
                        'physics_components': [
                            'homo_lumo_gap',
                            'frontier_orbital_degeneracy',
                            'open_shell',
                            'mean_field_fractional_occupations',
                            'correlated_natural_occupations',
                        ],
                        'solver_stress_components': [
                            'scf_convergence',
                            'spin_contamination',
                            'unrestricted_spin_symmetry_breaking',
                            'scf_stability',
                            'post_hf_convergence',
                            'ccsd_t1_d1',
                            'max_double_excitation_amplitude',
                            'correlation_energy_stress',
                        ],
                        'promotion_thresholds': {
                            'correlated_natural_occupation_moderate': 0.50,
                            'correlated_natural_occupation_strong': 0.80,
                            'ccsd_t1': 0.05,
                            'ccsd_d1': 0.10,
                        },
                        'routing_policy': {
                            'weak': 'ccsd_t',
                            'moderate': 'ccsd',
                            'strong': 'casscf_or_casci_after_active_space_approval',
                            'solver_stress_without_strong_physics': 'ccsd_before_multireference_promotion',
                        },
                        'execution_status_policy': {
                            'failed': 'strong_solver_stress',
                            'unconverged': 'strong_solver_stress',
                            'blocked': 'not_correlation_evidence',
                        },
                    },
                    'generated_output_rule': 'Correlation diagnostics are generated diagnostic outputs when the correlation_diagnostics field is present.',
                },
            ),
            _capability(
                'scf_stability',
                'SCF stability analysis',
                'molecular.workflow_option',
                description='Optional SCF stability analysis enabled through molecular.correlation_diagnostics module configuration.',
                ui_visibility='hidden',
                metadata={
                    'result_field': 'scf_stability',
                    'result_shape': 'diagnostic_summary',
                    'summary_fields': ['status', 'stable', 'internal_stable', 'external_stable', 'reason'],
                    'artifact_kinds': ['scf_stability'],
                    'generated_output_rule': 'SCF stability analysis is generated when the scf_stability field is present.',
                },
            ),
        ],
    }


__all__ = ['build_molecular_families']
