from __future__ import annotations

from typing import Any, Callable, Dict, List


def build_periodic_families(
    item_factory: Callable[..., Any],
    *,
    capability_design_only: str,
    capability_planned: str,
) -> Dict[str, List[Any]]:
    _capability = item_factory
    CAPABILITY_DESIGN_ONLY = capability_design_only
    CAPABILITY_PLANNED = capability_planned

    return {
        'periodic_methods': [
            _capability(
                'hf',
                'Periodic Hartree-Fock',
                'periodic.method',
                planner_allowed=False,
                limitations=['Initial implementation supports three-dimensional cells and Gamma or regular k-point meshes.'],
            ),
            _capability(
                'dft',
                'Periodic density functional theory',
                'periodic.method',
                planner_allowed=False,
                limitations=['Initial implementation supports three-dimensional cells and Gamma or regular k-point meshes.'],
            ),
        ],
        'periodic_jobs': [
            _capability(
                'single_point',
                'Periodic single-point energy',
                'periodic.job',
                planner_allowed=False,
            ),
        ],
        'periodic_observables': [
            _capability(
                'energy',
                'Total energy per cell',
                'periodic.observable',
                planner_allowed=False,
                metadata={
                    'result_field': 'energy',
                    'requestable_output': True,
                    'assistant_ui_output': False,
                    'result_shape': 'scalar',
                    'unit': 'Hartree/cell',
                    'supports_plot': ['line_plot', 'scatter_plot'],
                    'artifact_kinds': ['periodic_scf_summary'],
                    'generated_output_rule': 'Periodic HF/DFT produces the converged total energy per simulation cell.',
                },
            ),
            _capability(
                'band_gap',
                'Mean-field band gap',
                'periodic.observable',
                planner_allowed=False,
                metadata={
                    'result_fields': [
                        'band_gap',
                        'direct_gap',
                        'gap_type',
                        'is_metal',
                        'valence_band_max',
                        'conduction_band_min',
                        'band_edges',
                    ],
                    'requestable_output': True,
                    'assistant_ui_output': False,
                    'result_shape': 'scalar_group',
                    'unit': 'Hartree',
                    'supports_plot': ['line_plot', 'scatter_plot'],
                    'generated_output_rule': 'Mean-field fundamental and direct gaps are derived from spin- and k-point-resolved orbital energies and occupations over the executed SCF mesh.',
                },
            ),
            _capability(
                'fermi_energy',
                'Mean-field Fermi level',
                'periodic.observable',
                planner_allowed=False,
                metadata={
                    'result_fields': ['fermi_energy', 'fermi_energy_by_spin', 'fermi_energy_source'],
                    'requestable_output': True,
                    'assistant_ui_output': False,
                    'result_shape': 'scalar',
                    'unit': 'Hartree',
                    'supports_plot': ['line_plot', 'scatter_plot'],
                    'generated_output_rule': 'The mean-field Fermi level follows PySCF get_fermi; for integer occupations this uses the highest occupied level (VBM convention), with spin-resolved values retained for unrestricted references.',
                },
            ),
            _capability(
                'band_structure',
                'High-symmetry band structure',
                'periodic.observable',
                planner_allowed=False,
                metadata={
                    'result_fields': [
                        'band_path_mode',
                        'band_path',
                        'band_path_point_count',
                        'band_path_labels',
                        'band_structure_status',
                    ],
                    'requestable_output': True,
                    'assistant_ui_output': True,
                    'result_shape': 'band_path_summary',
                    'artifact_kinds': [
                        'periodic_band_structure',
                        'periodic_band_structure_tsv',
                    ],
                    'generated_output_rule': 'After a converged periodic HF/DFT calculation, evaluate mean-field bands on an automatic ASE path, a SeeK-path standardized primitive-cell path, a user-selected standard-point path, or an explicit reduced-coordinate path distinct from the SCF k mesh; reference plotted energies to the mean-field Fermi level.',
                },
            ),
            _capability(
                'periodic_band_structure_data',
                'Periodic band-structure data',
                'periodic.observable',
                ui_visibility='hidden',
                planner_allowed=False,
                metadata={
                    'result_field': 'periodic_band_structure',
                    'requestable_output': False,
                    'compact_result': False,
                    'result_shape': 'spin_kpath_bands',
                    'artifact_kinds': [
                        'periodic_band_structure',
                        'periodic_band_structure_tsv',
                    ],
                    'generated_output_rule': 'The selected path provenance, special-point coordinates, full high-symmetry path, absolute Hartree energies, and Fermi-referenced eV energies are preserved as dedicated artifacts.',
                },
            ),
            _capability(
                'periodic_structure',
                'Parsed periodic structure',
                'periodic.observable',
                ui_visibility='hidden',
                planner_allowed=False,
                metadata={
                    'result_field': 'periodic_structure',
                    'requestable_output': False,
                    'result_shape': 'cell_summary',
                    'artifact_kinds': [
                        'periodic_task_input',
                        'periodic_structure_source',
                        'periodic_cell',
                        'periodic_structure_normalized',
                        'periodic_input_cell',
                        'periodic_input_structure_normalized',
                        'periodic_seekpath_standardization',
                    ],
                    'generated_output_rule': 'The parsed cell, composition, Cartesian coordinates, and fractional coordinates are preserved as periodic structure artifacts. SeeK-path mode additionally preserves the input cell, effective standardized primitive cell, and transformation audit.',
                },
            ),
            _capability(
                'periodic_standardization',
                'Periodic cell standardization summary',
                'periodic.observable',
                ui_visibility='hidden',
                planner_allowed=False,
                metadata={
                    'result_field': 'periodic_standardization',
                    'requestable_output': False,
                    'result_shape': 'cell_standardization_summary',
                    'summary_fields': [
                        'library',
                        'recipe',
                        'spacegroup_number',
                        'spacegroup_international',
                        'bravais_lattice_extended',
                        'input_atom_count',
                        'primitive_atom_count',
                        'volume_original_wrt_primitive',
                        'reference_distance_1_per_angstrom',
                        'symprec_angstrom',
                        'path',
                        'explicit_point_count',
                        'warnings',
                    ],
                    'artifact_kinds': ['periodic_seekpath_standardization'],
                    'generated_output_rule': 'SeeK-path calculations expose a compact input-to-primitive-cell summary while preserving full transformation matrices in the dedicated audit artifact.',
                },
            ),
            _capability(
                'periodic_numerics',
                'Periodic numerical settings',
                'periodic.observable',
                ui_visibility='hidden',
                planner_allowed=False,
                metadata={
                    'result_field': 'periodic_numerics',
                    'requestable_output': False,
                    'result_shape': 'numerical_audit',
                    'summary_fields': ['precision', 'requested_ke_cutoff_hartree', 'fft_mesh', 'fft_mesh_source', 'density_fitting', 'exxdiv', 'smearing'],
                    'artifact_kinds': ['periodic_numerics'],
                    'generated_output_rule': 'Every periodic calculation records the effective integral precision, FFT mesh, density fitting, exact-exchange divergence, k-point, and smearing settings.',
                },
            ),
            _capability(
                'periodic_orbitals',
                'Periodic orbital spectrum',
                'periodic.observable',
                ui_visibility='hidden',
                planner_allowed=False,
                metadata={
                    'result_field': 'periodic_orbitals',
                    'requestable_output': False,
                    'compact_result': False,
                    'result_shape': 'spin_kpoint_bands',
                    'artifact_kinds': ['periodic_orbitals'],
                    'generated_output_rule': 'Periodic HF/DFT preserves mean-field orbital energies and occupations by spin and k-point as a dedicated artifact.',
                },
            ),
        ],
        'periodic_basis_sets': [
            _capability(
                'gth-szv',
                'GTH-SZV',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'standard'},
            ),
            _capability(
                'gth-dzv',
                'GTH-DZV',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'standard'},
            ),
            _capability(
                'gth-dzvp',
                'GTH-DZVP',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'standard'},
            ),
            _capability(
                'gth-tzvp',
                'GTH-TZVP',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'standard'},
            ),
            _capability(
                'gth-tzv2p',
                'GTH-TZV2P',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'standard'},
            ),
            _capability(
                'gth-qzv2p',
                'GTH-QZV2P',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'standard'},
            ),
            _capability(
                'gth-qzv3p',
                'GTH-QZV3P',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'standard'},
            ),
            _capability(
                'gth-aug-dzvp',
                'GTH-AUG-DZVP',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'augmented'},
            ),
            _capability(
                'gth-aug-tzvp',
                'GTH-AUG-TZVP',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'augmented'},
            ),
            _capability(
                'gth-aug-tzv2p',
                'GTH-AUG-TZV2P',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'augmented'},
            ),
            _capability(
                'gth-aug-qzv2p',
                'GTH-AUG-QZV2P',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'augmented'},
            ),
            _capability(
                'gth-aug-qzv3p',
                'GTH-AUG-QZV3P',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'augmented'},
            ),
            _capability(
                'gth-cc-dzvp',
                'GTH-CC-DZVP',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'correlation_consistent'},
            ),
            _capability(
                'gth-cc-tzvp',
                'GTH-CC-TZVP',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'correlation_consistent'},
            ),
            _capability(
                'gth-cc-qzvp',
                'GTH-CC-QZVP',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'correlation_consistent'},
            ),
            _capability(
                'gth-szv-molopt',
                'GTH-SZV-MOLOPT',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'molopt'},
            ),
            _capability(
                'gth-dzvp-molopt',
                'GTH-DZVP-MOLOPT',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'molopt'},
            ),
            _capability(
                'gth-tzvp-molopt',
                'GTH-TZVP-MOLOPT',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'molopt'},
            ),
            _capability(
                'gth-tzv2p-molopt',
                'GTH-TZV2P-MOLOPT',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'molopt'},
            ),
            _capability(
                'gth-szv-molopt-sr',
                'GTH-SZV-MOLOPT-SR',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'molopt_sr', 'broad_coverage': True},
            ),
            _capability(
                'gth-dzvp-molopt-sr',
                'GTH-DZVP-MOLOPT-SR',
                'periodic.basis',
                planner_allowed=False,
                metadata={'family': 'molopt_sr', 'broad_coverage': True},
            ),
        ],
        'periodic_pseudopotentials': [
            _capability(
                'gth-pade',
                'GTH-PADE',
                'periodic.pseudopotential',
                planner_allowed=False,
                metadata={'general': True, 'element_range': 'H-Rn', 'recommended_xc': ['lda']},
            ),
            _capability(
                'gth-lda',
                'GTH-LDA',
                'periodic.pseudopotential',
                planner_allowed=False,
                metadata={
                    'general': True,
                    'element_range': 'H-Rn',
                    'recommended_xc': ['lda'],
                    'alias_of': 'gth-pade',
                },
            ),
            _capability(
                'gth-pbe',
                'GTH-PBE',
                'periodic.pseudopotential',
                planner_allowed=False,
                metadata={'general': True, 'element_range': 'H-Rn', 'recommended_xc': ['pbe', 'pbe0']},
            ),
            _capability(
                'gth-pbesol',
                'GTH-PBEsol',
                'periodic.pseudopotential',
                planner_allowed=False,
                metadata={'recommended_xc': ['pbesol'], 'limited_coverage': True},
            ),
            _capability(
                'gth-blyp',
                'GTH-BLYP',
                'periodic.pseudopotential',
                planner_allowed=False,
                metadata={'recommended_xc': ['blyp'], 'limited_coverage': True},
            ),
            _capability(
                'gth-bp',
                'GTH-BP',
                'periodic.pseudopotential',
                planner_allowed=False,
                metadata={'xc_family': 'bp', 'limited_coverage': True},
            ),
            _capability(
                'gth-hcth120',
                'GTH-HCTH120',
                'periodic.pseudopotential',
                planner_allowed=False,
                metadata={'xc_family': 'hcth120', 'limited_coverage': True},
            ),
            _capability(
                'gth-hcth407',
                'GTH-HCTH407',
                'periodic.pseudopotential',
                planner_allowed=False,
                metadata={'xc_family': 'hcth407', 'limited_coverage': True},
            ),
            _capability(
                'gth-olyp',
                'GTH-OLYP',
                'periodic.pseudopotential',
                planner_allowed=False,
                metadata={'xc_family': 'olyp', 'limited_coverage': True},
            ),
            _capability(
                'gth-hf',
                'GTH-HF',
                'periodic.pseudopotential',
                planner_allowed=False,
                metadata={'recommended_method': ['hf'], 'limited_coverage': True},
            ),
            _capability(
                'gth-hf-rev',
                'GTH-HF-REV',
                'periodic.pseudopotential',
                planner_allowed=False,
                metadata={
                    'general': True,
                    'element_range': 'H-Rn',
                    'recommended_method': ['hf'],
                },
            ),
        ],
        'periodic_xc_functionals': [
            _capability('lda', 'LDA', 'periodic.xc', planner_allowed=False),
            _capability('pbe', 'PBE', 'periodic.xc', planner_allowed=False),
            _capability('pbesol', 'PBEsol', 'periodic.xc', planner_allowed=False),
            _capability('pbe0', 'PBE0', 'periodic.xc', planner_allowed=False),
            _capability('blyp', 'BLYP', 'periodic.xc', planner_allowed=False),
        ],
        'periodic_density_fitting_methods': [
            _capability('fft', 'FFTDF', 'periodic.density_fitting', planner_allowed=False),
            _capability('gdf', 'GDF', 'periodic.density_fitting', planner_allowed=False),
            _capability('mdf', 'MDF', 'periodic.density_fitting', planner_allowed=False),
            _capability('aft', 'AFTDF', 'periodic.density_fitting', planner_allowed=False),
        ],
        'periodic_kpoint_schemes': [
            _capability(
                'gamma_centered',
                'Gamma-centered',
                'periodic.kpoints',
                planner_allowed=False,
                metadata={'max_total_kpoints': 512},
            ),
            _capability(
                'monkhorst_pack',
                'Monkhorst-Pack',
                'periodic.kpoints',
                planner_allowed=False,
                metadata={'max_total_kpoints': 512},
            ),
        ],
        'periodic_band_path_modes': [
            _capability(
                'auto',
                'Automatic standard path',
                'periodic.band_path',
                planner_allowed=False,
                metadata={'path_source': 'ASE Bravais-lattice convention'},
            ),
            _capability(
                'seekpath',
                'SeeK-path standardized primitive cell',
                'periodic.band_path',
                planner_allowed=False,
                metadata={
                    'path_source': 'SeeK-path HPKOT convention',
                    'standardizes_cell': True,
                    'reference_distance_range_1_per_angstrom': [0.001, 0.5],
                    'symprec_range_angstrom': [1.0e-8, 0.1],
                },
            ),
            _capability(
                'custom',
                'Custom standard-point path',
                'periodic.band_path',
                planner_allowed=False,
                metadata={'path_source': 'User path over ASE-recognized special points'},
            ),
            _capability(
                'explicit',
                'Explicit special-point coordinates',
                'periodic.band_path',
                planner_allowed=False,
                metadata={'path_source': 'User path and reduced reciprocal coordinates'},
            ),
        ],
        'periodic_smearing_methods': [
            _capability('none', 'None', 'periodic.smearing', planner_allowed=False),
            _capability('fermi', 'Fermi-Dirac', 'periodic.smearing', planner_allowed=False),
            _capability('gaussian', 'Gaussian', 'periodic.smearing', planner_allowed=False),
        ],
        'periodic_exxdiv_options': [
            _capability('ewald', 'Ewald', 'periodic.exxdiv', planner_allowed=False),
            _capability('none', 'None', 'periodic.exxdiv', planner_allowed=False),
            _capability('vcut_sph', 'Spherical cutoff', 'periodic.exxdiv', planner_allowed=False),
            _capability('vcut_ws', 'Wigner-Seitz cutoff', 'periodic.exxdiv', planner_allowed=False),
        ],
    }


__all__ = ['build_periodic_families']
